### ISSUE TITLE
Bug: Logging error on / after shutdown

### ISSUE THREAD

**Issue by chekh** [airtai/faststream#1000]
**Describe the bug**
Provide a clear and concise description of the bug.

**How to reproduce**
Include source code:

```python

import anyio
from faststream import FastStream, Logger
from faststream.rabbit import RabbitBroker

broker = RabbitBroker()
app = FastStream(broker)


@app.on_shutdown
async def shutdown(logger: Logger):
    logger.info("Shutting down")
    await broker.close()


if __name__ == "__main__":
    anyio.run(app.run)

```

And/Or steps to reproduce the behavior:

1. Run app 
2. Stop app to start shutting down process3. Get error log 
3. Check logging messages

**Expected behavior**
Logger should perform logging until until the hooks end

**Observed behavior**
Logger raise exception if it called from function decorated as on_shutdown or after_shutdown.
Inspite of logger from faststream annotated type app.logger works properly.

```
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'exchange'
```

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by Lancetnik** [comment]
Just released: https://github.com/airtai/faststream/releases/tag/0.3.0rc0

Stable release should be in a few days
