### ISSUE TITLE
Feature: Reply-to delivery mode

### ISSUE THREAD

**Issue by ilyalatt** [airtai/faststream#1006]
**Is your feature request related to a problem? Please describe.**

Hello. I plan to use FastStream but encounter some problems.
Our team uses the RMQ `reply-to` header. We need FastStream replies to be persistent, but there is no way to configure it.

**Describe the solution you'd like**

Introduce a new `@app.subscriber` argument. `reply_to: ReplyToConfig` with `delivery_mode: aio_pika.DeliveryMode`.

**Comment by ilyalatt** [comment]
Okay. We can wait a few weeks. Thank you :)

**Comment by Lancetnik** [comment]
@ilyalatt Seems like I finished with the feature a little bit faster. You can try it with 0.3.1 release.

**Comment by ilyalatt** [comment]
@Lancetnik Good morning. Thank you! You made it really fast.
