### ISSUE TITLE
Feature: Skip RabbitQueue declaration

### ISSUE THREAD

**Issue by ilyalatt** [airtai/faststream#1007]
**Is your feature request related to a problem? Please describe.**

There is a coordinator that creates a queue with arguments. A worker needs to access the queue, and currently, queue arguments are duplicated in both the coordinator and the worker. We want to be able to configure the worker to not attempt to declare the queue (and not specify queue arguments in the worker).

**Describe the solution you'd like**

Add `declare: bool` field to `RabbitQueue`.

**Comment by Lancetnik** [comment]
@ilyalatt looks like we already have `passive` parameter for RabbitQueue and RabbitExcahnge both doing you want

**Comment by ilyalatt** [comment]
@Lancetnik Thank you
