### ISSUE TITLE
Bug: EmailStr is not added to summary when generating docs

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#1012]
**Describe the bug**
Provide a clear and concise description of the bug.

**How to reproduce**
Include source code:

```python
from faststream import FastStream
...
```

And/Or steps to reproduce the behavior:

1. ...

**Expected behavior**
Explain what you expected to happen clearly and concisely.

**Observed behavior**
Describe what is actually happening clearly and concisely.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by kumaranvpl** [comment]
This bug doesn't exists anymore.

I have tried to replicate the same across different python versions. `EmailStr` is included in docs summary(navigation) always. 

So closing this issue.
