### ISSUE TITLE
Replace aiokafka with confluent

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#1026]
Code:
- [x] Replace ConsumerRecord, _missing
  - [x] Make sure tests pass
- [x] Replace AbstractTokenProvider
  - [ ] Make sure tests pass
- [x] Use Confluent's KafkaException instead of aiokafka's KafkaError
  - [ ] Make sure tests pass
- [x] Add AsyncConfluentConsumer
  - [ ] Make sure tests pass
- [x] Add AsyncConfluentProducer
  - [x] Make sure tests pass
- [x] Use confluent_kafka.Message instead of aiokafka.ConsumerRecord in AsyncConfluentConsumer
- [x] Add confluent_broker.pyi

Static Analysis:
- [x] Fix failing mypy errors

Refactoring

- [x] please, split `faststream[kafka]` to `faststream[kafka]` and `faststream[confluent]` distributions
- [x] We already have `call_or_await` instead `asyncify`
- [x] we have a lot of warnings with topic config setup here seems like we shouldn't setup all these keys by default. Probably, we should separate it between
```python
self.config = { ... }
if sasl_mechanism:
    self.config.update({...})
if ...:
    self.config.update({...})
```
- [ ] we should use TypedDict this place
- [ ] Also, we should move topics creation from handler start to broker start.
- [ ] Documentation

**Comment by Lancetnik** [comment]
Should we replace it if aiokafka supports 3.12 now?

**Comment by davorrunje** [comment]
For now, we'll add an additional broker so people can use both AIOKafka and Confluent. AIOKafka is not well maintained and this is a big obstacle for many.
