### ISSUE TITLE
Feature: Option to disable only Access Logs.

### ISSUE THREAD

**Issue by ericsouza** [airtai/faststream#1037]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think a boolean option too disable access logging would be amazing, or maybe access logging should use a different logger with its own logger object.

**Feature code example**
```python
import logging
from faststream import FastStream, Logger
from faststream.nats import NatsBroker

my_logger = logging.getLogger("my_logger")

broker = NatsBroker("nats://localhost:4222/", logger=my_logger, disable_access_logs=True)
# or
# broker = NatsBroker("nats://localhost:4222/", logger=my_logger, access_logger=None)

app = FastStream(broker)

@broker.subscriber("in")
@broker.publisher("out")
async def handle_msg(user: str, user_id: int, logger: Logger) -> str:
    logger.info("testing")
    return f"User: {user_id} - {user} registered"
```

**Additional context**
I think this would help anyone that have limits with their logging storage or does not want to have too much unnecessary logs

**Comment by Lancetnik** [comment]
@ericsouza I have no reason to add this feature. For now, you already have an ability to filter access log messages from your log storage in a 2 ways:

1) downgrade access log message level with `Broker(log_level=logging.DEBUG)`. As an example, structlog doesn't create log message for disabled levels at all. Also, if you using syslog to transfer logs to your storage, not printed logs doesn't transfered to the storage too
2) You can disable broker logger, but set it to context manually:
```python
from faststream import ContextRepo, FastStream, Logger
from faststream.log import access_logger
from faststream.rabbit import RabbitBroker

broker = RabbitBroker(logger=None)
app = FastStream(broker)

@broker.subscriber("test")
async def handler(msg, logger: Logger):
    logger.info(msg)

@app.on_startup
def set_logger(context: ContextRepo):
    context.set_global("logger", access_logger)

@app.after_startup
async def t():
    await broker.publish("test", "test")
```
But, this way you are losing default FastStream log formating (but you can also setup it manually by getting access to `context.get_local("log_context")`

**Comment by ericsouza** [comment]
@Lancetnik Oh, this will do the job. Thanks!!

By the way, faststream is an amazing project. Thanks for all the work done by the team!!
