### ISSUE TITLE
Package anyio has not ExceptionGroup on Python >= 3.11

### ISSUE THREAD

**Issue by belinux** [airtai/faststream#1038]
**Description**
Run into some issues while dockering my application, it particularly triggered the exception at line following line [except anyio.ExceptionGroup as e:](https://github.com/airtai/faststream/blob/e7c05d6e5bd04edc2667d205a604c394b4013c6a/faststream/app.py#L349)

**How to reproduce**
Throw an error on startup.

```python
from faststream import FastStream
...
```

**Expected behavior**
Explain what you expected to happen clearly and concisely.

**Observed behavior**
Describe what is actually happening clearly and concisely.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by davorrunje** [comment]
Can you please tell us what versions of faststream and anyio are you using?

**Comment by belinux** [comment]
Hi, I'm sorry, I wrote the ticket in a rush, forgot to give more details. 
Packages versions are:

- Faststream: 0.3.3
- Anyio: 4.10

As mentioned, in app.py it's trying to use anyio.ExceptionGroup which is only available for versions under 3.12, and the imports in anyio on that version exclude that exception based on the python version. e.g.: [_trio.py:65](https://github.com/agronholm/anyio/blob/46a45c7454e4d87ab5671b158f746a2b3beaaae9/src/anyio/_backends/_trio.py#L65)

**Comment by davorrunje** [comment]
The problem was AnyIO upgraded to 4.x version. They introduced the following breaking change (https://anyio.readthedocs.io/en/stable/versionhistory.html):

BACKWARDS INCOMPATIBLE Replaced AnyIO’s own ExceptionGroup class with the PEP 654 BaseExceptionGroup and ExceptionGroup

It is fixed now, we'll release a new version in a few minutes.
