### ISSUE TITLE
Bug: raising NackMessage() ignores the retry parameter

### ISSUE THREAD

**Issue by sidjakinsboriss** [airtai/faststream#1046]
**Describe the bug**
If `NackMessage` is raised in the message handler, the `retry` parameter is ignored, and the messages keeps getting re-queued

**How to reproduce**
Include source code:

```python
@rabbit_router.subscriber(queue, exchange, retry=5)
async def handle_message(user: User, message: RabbitMessage):
    raise NackMessage()
```

**Expected behavior**
Message will be re-queued a maximum of `retry` times.

**Observed behavior**
Messaged is re-queued forever. 

**Additional context**
Happens because of this logic in `push_back_watcher.py`, so the number of retries is never checked:
```python
if not exc_type:
   await self.__ack()

elif isinstance(exc_val, SkipMessage):
    self.watcher.remove(self.message.message_id)

elif isinstance(exc_val, HandlerException):
    if isinstance(exc_val, AckMessage):
        await self.__ack()
    elif isinstance(exc_val, NackMessage):
        await self.__nack()
    elif isinstance(exc_val, RejectMessage):  # pragma: no branch
        await self.__reject()
    return True

elif self.watcher.is_max(self.message.message_id):
    await self.__reject()
```
Moreover, is `message.nack()` is called, `exc_type` is `None` and the first branch is taken calling `await self.__ack()`

**Comment by Lancetnik** [comment]
@sidjakinsboriss thank you for the Issue

I changed this behavior with 0.3.5 and now NackMessages also checks `is_max` condition

Btw, don't worry about default `self.__ack` - all messages can't be acked twice, so if you call `ack/nack/reject` manually, all following calls just do nothing
