### ISSUE TITLE
Feature: make routers independent from brokers

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#1047]
I would not expect a high level framework to expose these types of constructs (unless there are extra features specific to the underlying tech that I want to use - in which case why am I aiming for a high level library?). To continue with the SQLAlchemy example it would be like differentiating between a MysqlBaseModel and PostgresqlBaseModel instead of the generic sa.declarative.Base.

Ideally I'd expect to be able to do something like the following:

```python
# myapp/broker.py
from faststream import ...
from myapp.queues import router

def make_broker(config) -> Broker:
  if config["environment"] in {"local", "dev", "qa"}:
    broker = RedisBroker(**config["broker"]["kwargs"])
  else:
    broker = RabbitBroker(**config["broker"]["kwargs"])

  broker.include_router(router)
  return broker
```

Original post on Reddit: https://www.reddit.com/r/Python/comments/18gtrv0/comment/kd71ug8/

**Comment by Lancetnik** [comment]
Routers are already independent from broker. Btw, we already have a mechanism to delay broker configuration, so the Issue has no any sence
