### ISSUE TITLE
Bug:Batch Consumption of Kafka Messages Not Possible with FastAPI Plugin

### ISSUE THREAD

**Issue by JohannT9527** [airtai/faststream#1053]
**Describe the bug**
When utilizing the FastAPI plugin, FastStream currently places the message body in both the `body` and `query` request parameters simultaneously. However, during batch consumption, the message body is represented as a `List`, and attempting to convert it to `StreamMessage._query_params` results in an exception.

**How to reproduce**
Include source code:

```python
from typing import List
from fastapi import FastAPI
from pydantic import BaseModel
from faststream.kafka.fastapi import KafkaRouter


router = KafkaRouter('localhost:9092')


class Msg(BaseModel):
    id:int 

@router.subscriber('test', batch=True)
async def handle(msgs: List[Msg]):
    print(msgs)
    pass


app = FastAPI(lifespan=router.lifespan_context)
app.include_router(router)
```

And/Or steps to reproduce the behavior:

1. Start this FastAPI application and send a message.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

![image](https://github.com/airtai/faststream/assets/61002378/c15de5a4-6ee5-437c-96ae-9f72cfb04784)

It is possible that when batch consuming Kafka messages, query parameters can be set directly to an empty state.

**Comment by davorrunje** [comment]
@JohannT9527 thank you for the report, we'll look into it next week.

**Comment by Lancetnik** [comment]
Or we can fix it right now 😄 
Thank you for the Issue. I found a fix solving your case and we release it with 0.3.6
