### ISSUE TITLE
Feature: NATS broker publish accepts JStream object

### ISSUE THREAD

**Issue by Jonas1312** [airtai/faststream#1098]
Hi,

I wonder if `nats_broker.publish()` could accept `JStream` objects too?

https://github.com/airtai/faststream/blob/60ac362af12b4b2331a7bb88c3c20d12438dde9c/faststream/nats/broker.py#L476

Thanks!

**Comment by Lancetnik** [comment]
Hi! To be honest I don't like this idea and didn't implement it this thay specially
I don't wont to add extra check to each `broker.publish` method (everywhere) if user can just call
```python
broker.publish(..., stream=stream.name)
```
