### ISSUE TITLE
Feature: parallel message/request processing without throttling

### ISSUE THREAD

**Issue by baikov-ilia** [airtai/faststream#1099]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when discovered that there is no parallel processing out-of-box. Current implementation doesn't support that.

**Describe the solution you'd like**
Parallel processing regardless of previous message/request/etc processing incompleteness. May be pool feature like @Lancetnik said in [Discord](https://discord.com/channels/1085457301214855171/1093776044298862623/1188598667825909760). But actually it is should be possible to disable any throttling logic. Since we using it as RPC so throttling is handled by calling-side so its guaranted that RPC service wouldn't receive large amount of tasks.

**Feature code example**
This feature don't need to be implemented by user if we follow a FastStream, everything should be simple for the end developer.

```python
from faststream import FastStream, Logger
from faststream.nats import NatsBroker

broker = NatsBroker("nats://localhost:4222", name="Faststream Client")
app = FastStream(broker)

@broker.subscriber("process", queue="processing_queue")
async def test_subj(logger: Logger):        
    logger.info("Processing task")
    return {
        "id": "d9fa2659-959c-4edf-83e8-fe995dcf6eaf"
    }
```

**Describe alternatives you've considered**
I've considered for previous RPC implementation that using asyncio/ThreadPoolExecutor and so on instead of FastStream/Propan , but FastStream is a mindblowing tool that makes me stay using this project.

**Additional context**
No any other context

**Comment by Lancetnik** [comment]
Wait a bit - I already have a code implementing this feature) I have to test it before and release should be this week

**Comment by baikov-ilia** [comment]
> Wait a bit - I already have a code implementing this feature) I have to test it before and release should be this week

Sounds nice, LMK if i can help with something. At least testing stand is always on my hands

**Comment by baikov-ilia** [comment]
Seems like no change. No matter that `asyncio.sleep` or `time.sleep` is used, broker is still processed 1 message/request in synchornous manner.

**Comment by Lancetnik** [comment]
You should add `max_workers` option to your subscriber to create a pool explicitly

**Comment by baikov-ilia** [comment]
> You should add `max_workers` option to your subscriber to create a pool explicitly
It is, but probably something wrong 🤔 

```
@broker.subscriber("process", queue="processing_queue", max_workers=5)
async def test_subj(logger: Logger):        
    logger.info("Processing task")
    await asyncio.sleep(5)
    return {
        "id": "d9fa2659-959c-4edf-83e8-fe995dcf6eaf"
    }
```

```
$ faststream run main:app --reload
2023-12-27 22:30:19,910 ←[32mINFO    ←[0m - Will watch for changes in these directories: ['G:\\dev\\faststream-nats-example', '.']
2023-12-27 22:30:19,910 ←[32mINFO    ←[0m - Started reloader process [22792] using WatchFiles
2023-12-27 22:30:20,284 ←[32mINFO    ←[0m - FastStream app starting...
2023-12-27 22:30:20,320 ←[32mINFO    ←[0m - processing_queue | process |            - `TestSubj` waiting for messages
2023-12-27 22:30:20,320 ←[32mINFO    ←[0m - FastStream app started successfully! To exit, press CTRL+C
2023-12-27 22:31:02,588 ←[32mINFO    ←[0m - processing_queue | process | 6c19ef62-5 - Received
2023-12-27 22:31:02,590 ←[32mINFO    ←[0m - processing_queue | process | 6c19ef62-5 - Processing task
2023-12-27 22:31:07,604 ←[32mINFO    ←[0m - processing_queue | process | 6c19ef62-5 - Processed
2023-12-27 22:31:07,801 ←[32mINFO    ←[0m - processing_queue | process | 8a481c10-9 - Received
2023-12-27 22:31:07,802 ←[32mINFO    ←[0m - processing_queue | process | 8a481c10-9 - Processing task
2023-12-27 22:31:12,811 ←[32mINFO    ←[0m - processing_queue | process | 8a481c10-9 - Processed
2023-12-27 22:31:12,875 ←[32mINFO    ←[0m - processing_queue | process | cf3f9b96-7 - Received
2023-12-27 22:31:12,875 ←[32mINFO    ←[0m - processing_queue | process | cf3f9b96-7 - Processing task
2023-12-27 22:31:17,875 ←[32mINFO    ←[0m - processing_queue | process | cf3f9b96-7 - Processed
2023-12-27 22:31:17,938 ←[32mINFO    ←[0m - processing_queue | process | 7e5a743b-c - Received
2023-12-27 22:31:17,939 ←[32mINFO    ←[0m - processing_queue | process | 7e5a743b-c - Processing task
2023-12-27 22:31:22,952 ←[32mINFO    ←[0m - processing_queue | process | 7e5a743b-c - Processed
```

requirements.txt
```
annotated-types==0.6.0
anyio==4.2.0
click==8.1.7
colorama==0.4.6
fast-depends==2.2.8
faststream==0.3.11
idna==3.6
nats-py==2.6.0
pydantic==2.5.3
pydantic_core==2.14.6
sniffio==1.3.0
typer==0.9.0
typing_extensions==4.9.0
watchfiles==0.21.0
```

**Comment by Lancetnik** [comment]
I am trying to undestand yout problem, but in the clear environment your code works fine...

```python
from faststream import FastStream, Logger
from faststream.nats import NatsBroker
import asyncio

broker = NatsBroker()
app = FastStream(broker)


@broker.subscriber("process", queue="processing_queue", max_workers=100)
async def test_subj(logger: Logger):
    logger.info("Processing task")
    await asyncio.sleep(5)
    return {
        "id": "d9fa2659-959c-4edf-83e8-fe995dcf6eaf"
    }


@app.after_startup
async def t():
    for i in range(10):
        await broker.publish(i, "process")
```

All messages are processing in the same time

```
annotated-types   0.6.0
anyio             4.2.0
click             8.1.7
fast-depends      2.2.8
faststream        0.3.11
idna              3.6
nats-py           2.6.0
pip               23.2.1
pydantic          2.5.3
pydantic_core     2.14.6
setuptools        68.2.2
sniffio           1.3.0
typer             0.9.0
typing_extensions 4.9.0
```

**Comment by Lancetnik** [comment]
Did you install updated `requirements` file?

**Comment by baikov-ilia** [comment]
I've found what really can cause behaviour that i meet
When added:
```py
await broker.publish(i, "process", rpc=True)
```
it calls one by one. May be this is the issue ? Since all methods are being called through other SDK (nats.js for example)
```ts
for (let i = 0; i < 100; i++){
    nc.publish("process", jc.encode({ hello: "world"}));
}
```
 works as expected, but not in a RPC case, so it's just processing it like asynchronous events that dont need to return any response. But things got changed when you call it like RPC 
 ```ts
for (let i = 0; i < 5; i++){
    const res = await nc.request("process", jc.encode({ hello: "world"}), { timeout: 10_000});
    console.log("Res: ", jc.decode(res.data), "at ", new Date());
}
```

**Comment by Lancetnik** [comment]
Well, I'll try to fix it in the RPC case too

**Comment by Lancetnik** [comment]
But seems like your broker are processing messages concurrently and the block on the publisher side (cuz rpc requests waits for response and can't publish next message until it comes)

**Comment by baikov-ilia** [comment]
> But seems like your broker are processing messages concurrently and the block on the publisher side (cuz rpc requests waits for response and can't publish next message until it comes)

Yep, my bad. Refactored nats.js sample so it's proces now in some sort of pool that configured in `max_workers` 👍

**Comment by Lancetnik** [comment]
Is that the behavior you expect?

**Comment by baikov-ilia** [comment]
> Is that the behavior you expect?

Exactly!
If somebody will need to connect your Java RPC calls over FastStream using NATS as a broker there is code that cover concurrency case.
```java
List<CompletableFuture<Message>> messages = new ArrayList<>();
for(int i = 0; i < 100; i++) {
    String data = String.valueOf(i);
    CompletableFuture<Message> msg = this.nc.request("process", data.getBytes());
    messages.add(msg);
}
List<Message> res = messages.stream().map(CompletableFuture::join).toList();
```
@Lancetnik do you have buymeacoffee link ?

**Comment by Lancetnik** [comment]
> @Lancetnik do you have buymeacoffee link ?

Not yet, but I'll create it soon)
