### ISSUE TITLE
Feature: update permissions in gh actions

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#1146]
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
Provide a clear and concise description of the problem you've encountered. For example: "I'm always frustrated when..."

Github organization is going to update the default permission defined by the `permissions` block in all workflows by end of January. If this block is not specified, I believe some of our workflows will fail because they require write access (e.g., release). 

So, we will need to add a permission block to all workflows. Basically the [Github Docs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#permissions) seems to indicate that we should probably be very conservative about permissions. One way to know which permission is required is to set permission to empty and see what breaks, and only add relevant permission.

```yaml
name: "My workflow"

on: [ push ]

permissions: {}

jobs:
  ...
```

**Describe the solution you'd like**
Clearly and concisely describe the desired outcome or solution.

**Feature code example**
To help others understand the proposed feature, illustrate it with a **FastStream** code example:

```python
from faststream import FastStream
...
```

**Describe alternatives you've considered**
Provide a clear and concise description of any alternative solutions or features you've thought about.

**Additional context**
Include any other relevant context or screenshots related to the feature request.

**Comment by Lancetnik** [comment]
Can we closed it? Our workflows works fine and I settep up write premissions in worklows required it

**Comment by Lancetnik** [comment]
Please, reopen if it is required
