### ISSUE TITLE
Bug: json message destructuring doesn't work with single args

### ISSUE THREAD

**Issue by strangemonad** [airtai/faststream#1152]
**Describe the bug**

Following the filtering examples on https://faststream.airt.ai/latest/getting-started/subscription/filtering/

1) if entered as described -> the example works
2) if you change the msg to just be a single property eg `❯ nats pub "test" '{"name": "s"}' --header "content-type:application/json"` and similarly change the handler to a single arg

```python
@broker.subscriber(
    "test",
    filter=lambda msg: msg.content_type == "application/json",
)
async def handle(name: str):
    print("received json", name)


@broker.subscriber("test")
async def default(msg: str):
    print("received", msg)

```

The `kwargs` don't get unpacked in `CallModel.asolve` and the call is invoked with a `dict`, which raises a `ValidationError` (dict can't be assigned to str)

**Expected behavior**
Destructuring should work on single-property objects

**Environment**
```console
❯ poetry show faststream
 name         : faststream                                                   
 version      : 0.3.14                                                       
 description  : FastStream: the simplest way to work with a messaging queues 

dependencies
 - anyio >=3.7.1,<5
 - fast-depends >=2.2.6,<2.4.0
 - nats-py >=2.3.1,<3.0.0
 - typer >=0.9,<1
 - typing-extensions >=4.8.0

instance/services/web shawn/ot-cli-checkpoint*​​​ ≡
❯ 

instance/services/web shawn/ot-cli-checkpoint*​​​ ≡
❯ pr faststream -v              
Running FastStream 0.3.14 with CPython 3.11.6 on Darwin
```

**Comment by Lancetnik** [comment]
@strangemonad you are using serialization in a wrong way. Please, read #857

**Comment by strangemonad** [comment]
ah yeah, that totally makes sense that a single argument of an object vs a full message is ambiguous. given that at least 2 people have gotten tripped up by this, maybe this should be treated as a documentation bug?

**Comment by Lancetnik** [comment]
@strangemonad, thank you! This is a great point to improve the docs
