### ISSUE TITLE
Feature: add K8S probes checker API

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#1181]
We should provides users with an ability to check application health in a some way. It can be reached by using multiple mechanism, so we can create a base `Checker` Protocol and use it the following way

```python
app = FastStream(broker)
app.add_checker(
     SocketChecker("/sock"),
     # HTTPChecker(port=8000),
     # ...
)
```

And check all of them by the same command

```shell
faststream probe main:app
```

So, we can create multiple checkers for various cases and user can implement any checker by itself in the same time

* [x] add `broker.ping()` unified method
* [ ] add `BaseCheker` using `broker.ping()`
* [ ] implement `HTTPChecker` (inheritor of `BaseCheker`)
* [ ] add CLI command to use any checker

**Comment by Lancetnik** [comment]
Assigned to https://github.com/Sehat1137

**Comment by danb27** [comment]
I would love this feature! +1

**Comment by Lancetnik** [comment]
reassigned to @chudomozg
