### ISSUE TITLE
Feature: Load shedding / Message skipping

### ISSUE THREAD

**Issue by 4ydan** [airtai/faststream#1205]
**Is your feature request related to a problem? Please describe.**
Not that I am aware of.

**Describe the solution you'd like**
I would like to skip old messages so that my producer can keep up if the load is too high.

**Feature code example**
```python
from faststream import FastStream, Logger
from faststream.redis import RedisBroker, StreamSub

broker = RedisBroker("redis://localhost:6379")
app = FastStream(broker)

@broker.subscriber(stream=StreamSub("Bitmaps", group="bitmaps-consumer", consumer="1"), max_age=1)
@broker.publisher(stream="Points")
async def on_input_data(msg: Frame, logger: Logger) -> Points:
    logger.info(msg)
    image = image_cache.get(msg.memcached)
    return compute(image )
```

**One possible solution**
Once I process a new message where the timestamp is older than `max_age` I would discard all messages with the `>` operator so that I can catch up. This would involve to do something like the code below in "FastStream".
```
self.stream.xreadgroup(
  self.consumer_group,
  self.consumer_name,
  {self.consumer_topic: ">"},
  block=block,
  noack=noack,
)
LOGGER.info(f"Skipped {skipped_items} messages")
````
This is just a quick idea, there might be better solutions ofc.

**Describe alternatives you've considered**
Throw the messages away on my side before processing, but I still need to go over every single one. Maybe batch processing could be a solution.

**Additional context**
[Include any other relevant context or screenshots related to the feature request.](https://www.cs.yale.edu/homes/soule/pubs/csur2014.pdf)

This is maybe comparable to "Load shedding", where I shed some messages away, when I cant keep up with the load (page 24 of the above article).

**Comment by Lancetnik** [comment]
@4ydan hello! Sorry for waiting so long

I am not sure, that **FastStream** should add some extra arguments to filter incoming messages. You already have **filter** option to implement any case you want by yourself.

As an example: in you case you can filter too old messages this way

```python
from datetime import datetime, timedelta

from faststream import FastStream
from faststream.redis import RedisBroker, RedisMessage, StreamSub

broker = RedisBroker()
app = FastStream(broker)

async def filter_old(msg: RedisMessage) -> bool:
    # message_id is a timestamp - https://redis.io/docs/data-types/streams/#entry-ids
    published_ms_timestamp = float(msg.message_id.split("-")[0])
    published_data = datetime.fromtimestamp(published_ms_timestamp / 1000)
    return datetime.now() - published_data < timedelta(days=1)


@broker.subscriber(
    stream=StreamSub("Bitmaps", group="bitmaps-consumer", consumer="1"),
    filter=filter_old,
)
async def on_input_data(msg):
    """Your real logic consumer"""

@broker.subscriber(
    stream=StreamSub("Bitmaps", group="bitmaps-consumer", consumer="1"),
)
async def default_consumer(msg):
    """Use should create an empty default handler to ack skipped messages."""
```

**Comment by Lancetnik** [comment]
Also, you are still able to consume stream messages in batches and filter them from batch:

```python
from datetime import datetime, timedelta

from faststream import FastStream, Logger
from faststream.redis import RedisBroker, RedisMessage, StreamSub

broker = RedisBroker()
app = FastStream(broker)

async def filter_old(msg: RedisMessage) -> bool:
    filtered_body = []

    for msg_id, body in zip(msg.raw_message["message_ids"], msg.decoded_body):
        published_ms_timestamp = float(msg_id.split("-")[0])
        published_data = datetime.fromtimestamp(published_ms_timestamp / 1000)
        if datetime.now() - published_data < timedelta(days=1):
            filtered_body.append(body)

    msg.decoded_body = filtered_body

    return True


@broker.subscriber(
    stream=StreamSub("Bitmaps", group="bitmaps-consumer", consumer="1", batch=True),
    filter=filter_old,
)
async def on_input_data(msg):
    ...
```

**Comment by 4ydan** [comment]
Ah thank you, I was not aware of the RedisMessage type, that is amazing.

**Comment by Lancetnik** [comment]
@4ydan you do not need to change your consumer incoming message type. **RedisMessage** is a raw **FastStream** type using to [access low-level information](https://faststream.airt.ai/latest/redis/message/) or as a filter function single argument. So you can just add filter function to already written consumer.

**Comment by 4ydan** [comment]
Ok, I see, thank you.
This issue can be closed if its of no further interest for you.
