### ISSUE TITLE
Feature: Redis streams max length

### ISSUE THREAD

**Issue by 4ydan** [airtai/faststream#1235]
Any chance for getting capped redis streams or am I missing them and they are already implemented somewhere. In the src it seems like the parameter is not passed.

https://github.com/airtai/faststream/blob/b71505b7f538ffa7add5d3bef11c4692b95c13cf/faststream/redis/producer.py#L119

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to write to my stream with a set max length.

**Feature code example**

Maybe have a max_len variable in the publisher decorater?

```python
@broker.subscriber(stream="Input")
@broker.publisher(stream="Output", max_len=200)
async def on_input_data(msg: RedisMessage, logger: Logger) -> SomeType:
    ....
```

**Describe alternatives you've considered**
None

**Additional context**
[Redis doc](https://redis.io/docs/data-types/streams/#:~:text=N%20different%20consumers.-,Capped%20Streams,-Many%20applications%20do)

**Comment by Lancetnik** [comment]
@4ydan I implemented this in another way. You should use `StreamSub` object to specify any stream-specific options

```python
@broker.publisher(stream=StreamSub("Output", max_len=200))
async def on_input_data(msg: RedisMessage, logger: Logger) -> SomeType:
    ....
```
