### ISSUE TITLE
Feature: adding Kafka transactions.

### ISSUE THREAD

**Issue by spataphore1337** [airtai/faststream#1237]
I would like FastStream to support transactions from aiokafka. I assume that its implementation should not be complicated and it is realized by adding one method to broker or publisher.
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Clearly and concisely describe the desired outcome or solution.

**Feature code example**

At the moment there are no ideas about proper transaction design, but I will leave a link to the aiokafka documentation that shows how to work with transactions.

**Describe alternatives you've considered**
None.

**Additional context**
https://aiokafka.readthedocs.io/en/stable/examples/transaction_example.html

**Comment by spataphore1337** [comment]
I assume that it is necessary to add a method to AioKafkaFastProducer, which returns the called method in the producer aiokafka method transtaction, and already in the object KafkaBroker to make access to this method.

```
class AioKafkaFastProducer:
...
def transaction(self) -> TransactionContext:
   return self._producer.transaction()
```

**Comment by spataphore1337** [comment]
I assume that it is necessary to add a method to AioKafkaFastProducer, which returns the called method in the producer aiokafka method transtaction, and already in the object KafkaBroker to make access to this method.

class AioKafkaFastProducer:
...
def transaction(self) -> TransactionContext:
   return self._producer.transaction()

**Comment by Lancetnik** [comment]
Related to #1157

**Comment by Lancetnik** [comment]
I think, we can close it as a copy
