### ISSUE TITLE
Feature: support `last_id` for Redis stream consumer group

### ISSUE THREAD

**Issue by chrisgoddard** [airtai/faststream#1254]
Currently, you can set up a subscriber for a redis stream like this:

```python
@broker.subscriber(stream=StreamSub('stream-name', group='faststream', consumer='1'))
async def handle_msg(msg) -> None:
    logger.info(f"Received: {msg}")
```

However, if you try to past a `last_id` parameter:
```python
@broker.subscriber(stream=StreamSub('stream-name', group='faststream', consumer='1', last_id='0-0'))
async def handle_msg(msg) -> None:
    logger.info(f"Received: {msg}")
```

You get a warning:
`RuntimeWarning: `last_id` has no effect with consumer group`

It seems that in the redis/handler.py, it's hard-coding the '>' special id rather than passing through the last_id parameter (which it does when not using a consumer group)

```python
# redis/handler.py,
if stream.group and stream.consumer:
    read = client.xreadgroup(
        groupname=stream.group,
        consumername=stream.consumer,
        streams={stream.name: ">"},
        block=stream.polling_interval,
        noack=stream.no_ack,
    )

else:
    read = client.xread(
        {stream.name: self.last_id},
        block=stream.polling_interval,
    )
``

Is there a reason why we couldn't just pass self.last_id through to the dictionary and have last_id have the default value of ">"?

That way if you want to pull from a different offset while using a consumer group, you can.

**Comment by Lancetnik** [comment]
@chrisgoddard seems like we broke Redis Streams behavior:

Consumer group start position can be setted only by (`xgroup_create` command)[https://redis.io/docs/data-types/streams/#consumer-groups]

But, last_id should be always `>`.

>If the ID is the special ID > then the command will return only new messages never delivered to other consumers so far, and as a side effect, will update the consumer group's last ID.

> If the ID is any other valid numerical ID, then the command will let us access our history of pending messages. That is, the set of messages that were delivered to this specified consumer (identified by the provided name), and never acknowledged so far with [XACK](https://redis.io/commands/xack).

Specific ID is suitable only for one-time requests, but not regular consuming. I should rollback this behavior
