### ISSUE TITLE
Pytest dependency snuck through.

### ISSUE THREAD

**Issue by jmayo-benchsci** [airtai/faststream#1274]
https://github.com/airtai/faststream/blob/77d8a660f066e4ebe3dfbad879ff0e451d1ef8aa/faststream/redis/schemas.py#L5C1-L5C31

It looks like this line was added in error.

**Comment by Lancetnik** [comment]
Is was fixed in `0.4.5` release: https://github.com/airtai/faststream/blob/main/faststream/redis/schemas.py#L5
