### ISSUE TITLE
Feature: allow to use XXXDsn from Pydantic while specyfing the URL

### ISSUE THREAD

**Issue by ntoskrn** [airtai/faststream#1275]
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
Provide a clear and concise description of the problem you've encountered. For example: "I'm always frustrated when..."
I have an RabbitMQ broker, and I use Pydantic's AmqpDsn model for config validation. I would be really pleased if I could use AmqpDsn directly in Faststream

**Describe the solution you'd like**
Clearly and concisely describe the desired outcome or solution.

Just allow the URL param to accept XXX(broker) Dsn model instead of string or URL

**Feature code example**
To help others understand the proposed feature, illustrate it with a **FastStream** code example:

```python
from faststream import FastStream
from pydantic import AmqpDsn 
...
dsn = AmqpDsn.build(
    scheme="amqp",
    user="guest",
    password="guest",
    host="localhost",
    port=5672,
)

router = RabbitRouter(dsn)
```

**Comment by Lancetnik** [comment]
@ntoskrn thanks for the suggestion, but I think we should support only python-native types to require as less dependencies as possible. I was thinking about removing `URL` type (it exists only cuz it is supporting by `aio-pika`), more than, we are thinking about move `pydantic` to optional dependency, so it shouldn't be used everywhere directly.

Also, I don't see any problems to use smth like

```python
dsn = AmqpDsn.build(
    scheme="amqp",
    user="guest",
    password="guest",
    host="localhost",
    port=5672,
)

router = RabbitRouter(str(dsn))
```

if u want to use `AmqpDsn`.

I am sorry, but I am rejecting this suggestion. Anyway, be free to suggest anything u want else, I'll definitely think about all ideas.
