### ISSUE TITLE
Feature: broker syncify wrapper

### ISSUE THREAD

**Issue by allran** [airtai/faststream#1289]
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
Provide a clear and concise description of the problem you've encountered. For example: "I'm always frustrated when..."

**Describe the solution you'd like**
Clearly and concisely describe the desired outcome or solution.

**Feature code example**
To help others understand the proposed feature, illustrate it with a **FastStream** code example:

```python
from faststream import FastStream
...
```

**Describe alternatives you've considered**
Provide a clear and concise description of any alternative solutions or features you've thought about.

**Additional context**
Include any other relevant context or screenshots related to the feature request.

**Comment by Lancetnik** [comment]
We were thinking about it, but consider to support only async API
Is it problem for you?

**Comment by allran** [comment]
Because when sending a message, I need the following encapsulation to work properly:
```
broker = RabbitBroker(broker_url)
def publish_msg(*args, **kwargs):
    """
    发送消息
    """
    async def send_msg():
        #
        broker_pub = kwargs.get('broker', None)  # 是否有传入broker
        if broker_pub is None and len(args) > 0:
            bro = args[0]
            if isinstance(bro, RabbitBroker):  # 传入的第一个参数,是否是broker
                broker_pub = bro
        if broker_pub is None:
            async with RabbitBroker(broker_url) as broker_pub:
                await broker_pub.publish(*args, **kwargs)
        else:
            await broker.connect()
            await broker.publish(*args, **kwargs)

    asyncio.run(send_msg())

if __name__ == "__main__":
    publish_msg("messageOne", "in")
```

**Comment by Lancetnik** [comment]
I have a plan to add syncify class from [this discussion](https://github.com/airtai/faststream/discussions/854). Now you can use it by youself

**Comment by allran** [comment]
ok, thanks very much. @Lancetnik
