### ISSUE TITLE
Bug: FastAPI integration failed to start because of non-existed logger

### ISSUE THREAD

**Issue by DmitriyKalekin** [airtai/faststream#1305]
**Describe the bug**
All the examples of FastAPI integration (I used from github and documentation) were failed with error:
_AttributeError: 'FastAPI' object has no attribute 'logger' AttributeError: 'FastAPI' object has no attribute 'logger'_

**How to reproduce**
Include source code:

```python
from fastapi import FastAPI
from faststream.nats.fastapi import NatsRouter, Logger

router = NatsRouter("nats://localhost:4222")
app = FastAPI(lifespan=router.lifespan_context)
publisher = router.publisher("response-q")


@publisher
@router.subscriber("test-q")
async def handler(user_id: int, logger: Logger):
    logger.info(user_id)
    return f"{user_id} created"

app.include_router(router)
...
```

And/Or steps to reproduce the behavior:

1. Run any example of FastAPI integration from /examples folder or from official FastStream docs.

**Expected behavior**
Application must be started without this error. 

**Observed behavior**
Failed to start with: _AttributeError: 'FastAPI' object has no attribute 'logger' AttributeError: 'FastAPI' object has no attribute 'logger'_

**Environment**
Python version is 3.12
Docker python:3.12-slim
faststream[nats]==0.4.7
fastapi==0.110.0

**Additional context**
I use docker. Nats container started ok, Nats server is available in the network. Container with application cannot be started because of this error.

**Comment by Lancetnik** [comment]
@DmitriyKalekin are you running **FastAPI** object by `faststream run ...`? It's not ASGI server and can works only with **FastStream** object

**Comment by DmitriyKalekin** [comment]
Yes. You are right. I used` faststream run ...`. 
Launch with uvicorn works fine. 
Thank you!

P.S. I think It's good idea to update the documentation to show that only uvicorn-launch is suitable
https://faststream.airt.ai/latest/getting-started/integrations/fastapi/
