### ISSUE TITLE
Feature: Allow passing kwargs to underlying broker library

### ISSUE THREAD

**Issue by surculus12** [airtai/faststream#1337]
Currently, there seems to be no way to pass security-related information (JWT keys, nkeys, etc.) to the underlying NATS library. There is no specific support for it (see #780), nor does there seem to be a way to pass data down to the broker yourself via kwargs.

**Is your feature request related to a problem? Please describe.**
I can't use NATS security features, or other features that faststream hasn't specifically implemented.

**Describe the solution you'd like**
Either something like:
```
broker = NatsBroker('nats://whatever', kwarg1='a', ...)
await broker.start()
```
where the unknown kwargs are popagated to `self.connect(...)` inside `broker.start()` or
```
await broker.start(kwarg1='a', ...)
```
with the same propagation.

**Comment by Lancetnik** [comment]
We already have documentated way to make the thing you want: just pass all arguments to `broker.connect(...)` in `@app.on_startup` hook (https://faststream.airt.ai/latest/getting-started/lifespan/hooks/?h=%40app+on_startup#lifespan)

`broker.start` is a wrong place to make this due it is a method to "start all subscribers", not connect to the broker (but it uses `broker.connect` inside, it's true). If you want to pass "connection parameters", please, use semantically correct method.

**Comment by surculus12** [comment]
I miss that. That's perfect, thanks.
