### ISSUE TITLE
Feature: Deferred initialization of topic names

### ISSUE THREAD

**Issue by johanjk** [airtai/faststream#1343]
When establishing a connection, this can be deferred to the lifespan hook using `broker.connect`

Likewise, I would like to defer the selection of topic names until the lifespan hook.

**Comment by Lancetnik** [comment]
We have a way to delay subscribers declaration already: https://faststream.airt.ai/latest/getting-started/routers/#router-usage

Please, use it if you don't like to setup your topics from global config
