### ISSUE TITLE
Bug: Publisher Direct Usage

### ISSUE THREAD

**Issue by taras0024** [airtai/faststream#1384]
**Describe the bug**
Can't use direct publishing
[Documentation](https://faststream.airt.ai/latest/getting-started/publishing/direct/)

**How to reproduce**

```python
from faststream import FastStream
from faststream.rabbit import RabbitBroker


broker = RabbitBroker("amqp://guest:guest@localhost:5672")
app = FastStream(broker)

await broker.connect()

publisher = broker.publisher("another-queue")

@broker.subscriber("another-queue")
async def handle_next(msg: str):
    assert msg == "Hi!"

await publisher.publish("Hi")
```

Error:

```
AssertionError: Please, `connect()` the broker first
```

*When added publisher setup*:

```python
from faststream import FastStream
from faststream.rabbit import RabbitBroker


broker = RabbitBroker("amqp://guest:guest@localhost:5672")
app = FastStream(broker)

await broker.connect()

publisher = broker.publisher("another-queue")


@broker.subscriber("another-queue")
async def handle_next(msg: str):
    assert msg == "Hi!"

publisher.setup(producer=broker._producer, app_id=broker.app_id, virtual_host=broker.virtual_host)

await publisher.publish("Hi")
```

Output:
```
DeliveredMessage(delivery=<Basic.Return object at 0xffff6e0be3f0>, header=<pamqp.header.ContentHeader object at 0xffff6fa5c590>, body=b'Hi', channel=<Channel: "1" at 0xffff6e2350e0>)
```

**Screenshots**
<img width="667" alt="image" src="https://github.com/airtai/faststream/assets/74822918/28da790c-befc-482e-a6ff-5bcb31f8f98f">
<img width="824" alt="image" src="https://github.com/airtai/faststream/assets/74822918/2c29b1b4-057a-4c93-a562-b92bbac587b8">

<img width="1238" alt="image" src="https://github.com/airtai/faststream/assets/74822918/1b9795ed-4348-43f3-8a23-62700b26c766">

**Comment by Lancetnik** [comment]
Sorry, but you can't use `publisher` and other objects as well until broker is not started. This is the core limitation of **FastStream**, but if you faced with it - you are trying to make really strange thing

**Comment by Lancetnik** [comment]
Seems like we should correct message to use `broker.start()` before using publisher.

**Comment by Lancetnik** [comment]
Anyway, instead of

```python
publisher.setup(producer=broker._producer, app_id=broker.app_id, virtual_host=broker.virtual_host)
# you should use
broker.setup_publisher(publisher)
``

Also, I moved setup hook from start to connect method, so the error message tells the truth now
