### ISSUE TITLE
Bug: FastStream global context set is not access in pytest

### ISSUE THREAD

**Issue by kusime** [airtai/faststream#1403]
**Describe the bug**

only run with `faststream run main:app` can avoid this bug , i think this cause by the pytest is not access the app . so there is no Context is injected. is there any way in pytest to access the Global Context ?

**How to reproduce**
Include source code:

```python
app = FastStream(broker)

@app.on_startup
async def set_global(context: ContextRepo):
    context.set_global("secret_str", "my-perfect-secret")

@broker.subscriber("test")
async def vaea(
    msg: dict,
    secret_str: Annotated[str, Context("secret_str")],
):
    assert secret_str == "my-perfect-secret"
```

```python
@pytest.mark.asyncio
async def test_dependency():
    async with TestRabbitBroker(broker, with_real=True) as br:
        # message can not be None
        await br.publish({}, queue="test")
        await vaea.wait_call(timeout=3)
        vaea.mock.assert_called_once_with({})
```

And/Or steps to reproduce the behavior:

1. ...

**Expected behavior**
In pytest , the global context should accessable

**Observed behavior**
can not access the global context  variable , and cause missing field error

**Screenshots**
![image](https://github.com/airtai/faststream/assets/60957601/8c8e8781-3d26-4603-aa40-939dd476e297)

**Environment**
Running FastStream 0.5.3 with CPython 3.11.0 on Windows

**Additional context**

**Comment by Lancetnik** [comment]
Please, take a look at this [documentation section](https://faststream.airt.ai/latest/getting-started/lifespan/test/)

It talks about how you can run and test your application lifespan hooks
