### ISSUE TITLE
Kafka Test Subscriber doesn't match Consumer Group behaviour 

### ISSUE THREAD

**Issue by sinnwise** [airtai/faststream#1412]
Currently the Kafka Test Publisher / Subscriber combo returns early upon hitting a subscriber / topic combination.

If an application has two subscribers, across two `consumer-group`s listening on a single topic, FastStream does not respect that both subscribers should receive a message each from the topic. In testing only the first-matched topic would run.

https://github.com/airtai/faststream/blob/ed270add879eb48f5a0f6ce07564ab5625be5049/faststream/kafka/testing.py#L94-L102

Removing the `return` and letting each Subscriber handle the alert seems to get me closer to working behaviour (essentially we will have to create a list of subscribers attached to consumer groups and run `handle` on the first one in each consumer group – not sure how filters should come into play here).

Will work on a PR soon ☺️

**Comment by sifex** [comment]
PR opened on my non-work account.

**Comment by Lancetnik** [comment]
Thank you for the Issue and for the PR as well! I'll take a look close soon, sorry for waiting
