### ISSUE TITLE
Feature: make typer optional and move to `faststream[cli]` distribution

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#1430]
Also we should update documentation accordingly

**Comment by Lancetnik** [comment]
I think, we should remove CLI typer dependency from default destribution and move it to `faststream[cli]` optionals (with watchfiles probably)

**Comment by RubenRibGarcia** [comment]
Hey @Lancetnik, I would like to contribute to this repository and would like to pick this issue. I already start working on this probably by the end of this week I might open a PR.

**Comment by Lancetnik** [comment]
@RubenRibGarcia thank you for your interest! I will wait for PR from you 😄
