### ISSUE TITLE
Feature: add `Response` class

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#1431]
We should create a special class to make users able to setup outgoing message metainformation in `@publihser` decorator case

```python
@broker.publisher("out")
@broker.subscriber("in")
async def handler(msg) -> Reponse:
    return Reponse(data=b"", headers={})
```

Also, the basic case with *just a data* should be supported as well

```python
@broker.publisher("out")
@broker.subscriber("in")
async def handler(msg):
    return b""   # should works
```

More than we should create specific `KafkaResponse`/`RabbitResponse`/... classes to allow user to specify broker-specific information like in the following example

```python
@kafka_broker.publisher("out")
@kafka_broker.subscriber("in")
async def handler(msg) -> Reponse:
    return KafkaResponse(data=b"", headers={}, key=b"")
```

P.S. RMQ ReplyConfig option should be deprecated

**Comment by AmanSal1** [comment]
@Lancetnik Can I give this a shot? Could you just brief me a little bit about this?

**Comment by Lancetnik** [comment]
@AmanSal1 sorry, I was a little hasty. It's not so easy to implement as I thought. It requires coordinated changes in all publishers, so I'll implement it by myself.

If you want to help, you create create a basic `Response` class in `broker/response.py` with `__new__` method, that could consume raw data or `Response` class instance and return `Response` itself if it was passed or create a new one from data (you can take a look [here](https://github.com/airtai/faststream/blob/main/faststream/broker/wrapper/call.py#L37) for reference)

**Comment by AmanSal1** [comment]
@Lancetnik 
```
class Response:
    def __new__(cls, *args, **kwargs):
        if len(args) == 1 and isinstance(args[0], cls):
            # If an instance of Response is passed, return it directly
            return args[0]
        else:
            # Otherwise, create a new instance with the provided data
            return super().__new__(cls)

    def __init__(self, data=None, headers=None, key=None):
        self.data = data
        self.headers = headers or {}
        self.key = key
```

Could you please check if this is what you meant? For the next part, I suppose we would need to create separate classes for each and inherit the response class for them. Then, we would have to modify the decorator class for each response class

**Comment by Lancetnik** [comment]
Yeah, something like this

**Comment by Lancetnik** [comment]
@AmanSal1 thank you for the interest! I make a draft release of Response classes, as u can see, but we still need to specify broker-specific options in `[Broker]Response` class. You can take care on it, if you want
