### ISSUE TITLE
Fix - Check docs for broken links is failing

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#1438]
This has been failing for a month.
It started happening after a specific point - https://github.com/airtai/faststream/actions/workflows/check-broken-links-in-docs.yaml

**Comment by Lancetnik** [comment]
Should/Can we make smth here?

**Comment by kumaranvpl** [comment]
> Should/Can we make smth here?

I will look into it as soon as possible.

**Comment by kumaranvpl** [comment]
Reopening this as some links are still failing - https://github.com/airtai/faststream/actions/runs/10526298650/job/29166881965

**Comment by Lancetnik** [comment]
😢

**Comment by kumaranvpl** [comment]
Check docs for broken links is passing now - https://github.com/airtai/faststream/actions/runs/10636063734/job/29487045969
