### ISSUE TITLE
Feature: Provide a way to customize logging in confluent's Consumer and Producer objects

### ISSUE THREAD

**Issue by andreaimprovised** [airtai/faststream#1449]
**Is your feature request related to a problem? Please describe.**

Confluent's library likes to pollute stdout with a bunch of lines like this:

```
%3|1715814665.276|FAIL|faststream-0.5.5#consumer-5| [thrd:localhost:30100/bootstrap]: localhost:30100/bootstrap: Connect to ipv6#[::1]:30100 failed: Connection refused (after 3ms in state CONNECT, 1 identical error(s) suppressed)
```

We do structured logging at my company, and these lines basically muck up the logs which are otherwise in a common format.

We intercept all standard library loggers, so I don't really need to the ability to pass in a custom one as long its name is prefixed with faststream. We just need something passed in at all.

**Describe the solution you'd like**

Confluent has supported passing in a customer logger since 2018 it would appear:

https://github.com/confluentinc/confluent-kafka-python/issues/148

I have tested this out as well on a local build of faststream where I have the AsyncConfluentConsumer and AsyncConfluentProducer objects pass a logger kwarg.

```python
        create_topics(topics=self.topics, config=self.config)
        self.consumer = Consumer(
            self.config,
            logger=logging.getLogger("faststream.confluent.client.consumer")
        )
```

Which would produce a line like this (using our company's console log formatting):

```
2024-05-15 16:04:39.218 | ERROR    | faststream.confluent.client.consumer | _asyncio.run:851 | FAIL [faststream-0.5.5#consumer-5] [thrd:localhost:30100/bootstrap]: localhost:30100/bootstrap: Connect to ipv6#[::1]:30100 failed: Connection refused (after 1ms in state CONNECT)
```

And in production we'd have it output in JSON format.

**Feature code example**

It would be a completely under-the-hood change. Optionally, could reuse the same custom logger that is passed into to the `KafkaBroker` object.

**Describe alternatives you've considered**

I have no idea how else to intercept Confluent logging.

**Additional context**

n/a

**Comment by Lancetnik** [comment]
Great point, we should pass KafkaBroker.logger to underlying classes to reuse it. It should be easy-to-add, I suppose
