### ISSUE TITLE
Bug: fake consumer doesn't account for routing key

### ISSUE THREAD

**Issue by Klavionik** [airtai/faststream#1480]
**Describe the bug**
It seems like the fake consumer created by the test RabbitMQ broker doesn't take in account the publisher's `routing_key`, only the `queue` attribute.

This leads to failed assertions about the call count when testing publishers that publish messages with a routing key. 

**How to reproduce**
```python
from faststream.rabbit import TestRabbitBroker, RabbitBroker, RabbitExchange, ExchangeType

dsn = "amqp://guest:guest@0.0.0.0:6666/"
broker = RabbitBroker(url=dsn)
publisher = broker.publisher(exchange=RabbitExchange("test_exchange", type=ExchangeType.TOPIC), routing_key="update")


async def test_publisher():
    async with TestRabbitBroker(broker):
        for i in range(10):
            await publisher.publish(f"message {i}")

        assert publisher.mock.call_count == 10
```

Running this test gives you an assertion error: `AssertionError: assert 0 == 10`.

**Expected behavior**
Fake test queue has a routing key of its publisher.

**Observed behavior**
Fake test queue doesn't have a routing key of its publisher, therefore it doesn't consume published messages.

**Environment**
`Running FastStream 0.5.7 with CPython 3.12.0 on Darwin`

**Comment by Klavionik** [comment]
By the way, a question. Is there a point of having `queue` parameter for publishers? I'm not a RabbitMQ expert, but I was always thinking that RabbitMQ publishers don't care about queues, they publish to exchanges. Queues exist only on the consumers' side. Maybe I'm missing something here?

**Comment by Lancetnik** [comment]
Thank you for the report! I'll fix it soon

Queue is just an alias to routing key - we have it in the doc: https://faststream.airt.ai/latest/rabbit/publishing/#rabbit-publishing

**Comment by Klavionik** [comment]
I see now, thank you for pointing it out! I would still argue that this is rather confusing. One could pass not only a plain string, but also a `RabbitQueue` object via this parameter, with all the stuff that publishers don't care about. 

I believe it would be much clearer to have only `routing_key` for publishers.
