### ISSUE TITLE
Feature: Support for disabling automatic topic creation.

### ISSUE THREAD

**Issue by andreaimprovised** [airtai/faststream#1486]
**Is your feature request related to a problem? Please describe.**

We're using the confluent kafka backend, so this is relative to that. Haven't looked at aiokafka.

- FastStream will auto-create topics using confluent's AdminClient interface prior to instantiating the confluent Consumer object.
- FastStream hardcodes "allow.auto.create.topics" to True in the config it passes to the confluent Consumer. If this is also set to True on the brokers, this allows the confluent_kafka library itself to auto create topics as well at subscription time.
- FastStream does not set "allow.auto.create.topics" in the confluent Kafka Producer config. It's default value is True, however. Similarly, if also set to True on brokers, this allows auto create of topics as well at message production time.
- broker.subscriber() and broker.producer() provide no facilities to modify the above behavior.

We generally don't want to allow automatic topic creation in our production environment, or at least, we may want to disallow it and have knobs to control these things.

Moreover, I am curious why FastStream doesn't do admin-client based auto topic creation prior to making a confluent Producer object. Is there a reason. It's not something I care about directly.

**Describe the solution you'd like**

I'd like additional broker.subscriber() and broker.producer() kwargs that provide knobs to these settings where currently none exist.

**Feature code example**

Something like this:

```python
from faststream import FastStream
from faststream.confluent import KafkaBroker
from faststream import Logger

broker = KafkaBroker()

@broker.subscriber(
    'my-topic',
    # If True, allow FastStream to create topics using the admin client if they don't already exist
    admin_create_topics=False,
    # if True, allow confluent_kafka to auto create topics if the broker also allows it
    allow_auto_create_topics=False,
)
@broker.producer(
    'my-other-topic',
    # if True, allow confluent_kafka to auto create topics if the broker also allows it
    allow_auto_create_topics=False
)
async def hello(body: str, logger: Logger):
    logger.info('hello')
    return 'output'

app = FastStream(broker)
```

It would be a relatively simple modification, just passing around some additional parameters and doing some conditional branching.

**Describe alternatives you've considered**

I have patched such things manually to get the desired effect in lieu of direct support:

```python
import os

from faststream.confluent.client import create_topics
from confluent_kafka import Consumer, Producer
import faststream.confluent.client

from observing.environment import BUILD_ENV, BuildEnv
from observing.observing import logger as module_logger


def create_topics_patch(*args, **kwargs):
    if BUILD_ENV == BuildEnv.PRODUCTION or "IS_TEST" in os.environ:
        module_logger.warning(
            f"faststream.confluent.client.create_topics():"
            f" Automatic topic creation is disabled."
        )
    else:
        create_topics(*args, **kwargs)


class PatchedConfluentConsumer(Consumer):

    def __init__(self, config, logger=None):
        config = config.copy()

        if BUILD_ENV == BuildEnv.PRODUCTION or "IS_TEST" in os.environ:
            if config.get("allow.auto.create.topics"):
                module_logger.warning(
                    f"confluent_kafka.Consumer.__init__():"
                    f" Automatic topic creation is disabled."
                )
            config["allow.auto.create.topics"] = False

        super().__init__(config, logger=logger)


class PatchedConfluentProducer(Producer):

    def __init__(self, config, logger=None):
        config = config.copy()

        if BUILD_ENV == BuildEnv.PRODUCTION or "IS_TEST" in os.environ:
            if config.get("allow.auto.create.topics"):
                module_logger.warning(
                    f"confluent_kafka.Producer.__init__():"
                    f" Automatic topic creation is disabled."
                )
            config["allow.auto.create.topics"] = False

        super().__init__(config, logger=logger)


def patch_conditionally_disabled_topic_creation():
    """Makes it so FastStream will only automatically create topics when Consumers are
    running in a non-production environment and when not running tests.

    This is useful for preventing accidental topic creation in production environments
    and during tests.

    FastStream, when creating a confluent Consumer, will call create_topics() which
    allows for the broker.subscriber() call to pass some topic creation configuration
    settings. This is disabled in production environments by this patch.

    FastStream will also set the allow.auto.create.topics configuration setting to
    True when creating a Confluent Kafka Consumer, and it does not touch the default
    value of True for Confluent Kafka Producers. These settings require the broker to
    be configured to allow for automatic topic creation as well to have any effect.
    This patch will set the allow.auto.create.topics to False when in a production
    environment, no matter what, for both Consumer and Producer. Topics must only be
    created manually in production environments.
    """
    faststream.confluent.client.create_topics = create_topics_patch
    faststream.confluent.client.Consumer = PatchedConfluentConsumer
    faststream.confluent.client.Producer = PatchedConfluentProducer

```

**Additional context**
None.

**Comment by andreaimprovised** [comment]
Ooo, relevant context here y'all

I tried doing automated testing of this code against a real broker, and I kept running into segfaults under the environmental conditions where I didn't want create_topics to run.

I think it is related to an issue on confluent-kafka-python:

https://github.com/confluentinc/confluent-kafka-python/issues/1547

I hopped into lldb to debug the issue, and this is where the call dies in confluent_kafka:

```
* thread #8, stop reason = EXC_BAD_ACCESS (code=1, address=0xae0)
  * frame #0: 0x000000011002fec4 librdkafka.dylib`rd_kafka_q_pop_serve + 888
    frame #1: 0x0000000110005420 librdkafka.dylib`rd_kafka_consume0 + 236
    frame #2: 0x00000001069a2024 cimpl.cpython-312-darwin.so`Consumer_poll + 132
    frame #3: 0x0000000101a36d8c libpython3.12.dylib`cfunction_call + 72
    frame #4: 0x00000001017d9588 libpython3.12.dylib`_PyObject_MakeTpCall + 364
    frame #5: 0x00000001020ffd60 libpython3.12.dylib`context_run + 104
    frame #6: 0x0000000101a5d768 libpython3.12.dylib`cfunction_vectorcall_FASTCALL_KEYWORDS.llvm.9583944732609251760 + 92
    frame #7: 0x000000010187c4ec libpython3.12.dylib`_PyEval_EvalFrameDefault + 177028
    frame #8: 0x0000000101a4787c libpython3.12.dylib`method_vectorcall.llvm.1905976008390717660 + 372
    frame #9: 0x00000001019bd1fc libpython3.12.dylib`thread_run + 128
    frame #10: 0x000000010210ec10 libpython3.12.dylib`pythread_wrapper.llvm.5502682215143329338 + 48
    frame #11: 0x000000019430ef94 libsystem_pthread.dylib`_pthread_start + 136
```

The application will basically just die in fairly unpredictable locations, so I think it's maybe a thread outside of the main event loop thread.

So, in all likelihood, people's FastStream applications will just outright segfault if they haven't created the topics ahead of time.

Which, I dunno, is just something to be aware of?

**Comment by kumaranvpl** [comment]
@andreaimprovised We were aware that if the topic doesn't exists then confluent-kafka-python will segfault. That is why only we decided to create topics while initializing our async wrapper.

**Comment by kumaranvpl** [comment]
Hello @andreaimprovised,

This is fixed and I have added a new param to disable automatic topic creation.

```python
from faststream import FastStream
from faststream.confluent import KafkaBroker

broker = KafkaBroker(allow_auto_create_topics=False)
app = FastStream(broker)
```

Above code disables automatic topic creation.
