### ISSUE TITLE
Feature: subscribe and produce to different broker

### ISSUE THREAD

**Issue by yuyupopo** [airtai/faststream#1491]
**Is your feature request related to a problem? Please describe.**

I want to subscribe from a rabbitmq queue and publish the message to a kafka broker. Also it would be nice if `FastStream` app can support multiple brokers.

**Feature code example**

```python
broker1 = KafkaBroker(...)
broker2 = RabbitBroker(...)

@broker1.publisher(...)
@broker2.subscriber(...)
async def handler(event: str) -> str:
    return event
```

Thank you for the awesome project!

**Comment by Lancetnik** [comment]
Hi, @yuyupopo ! Thank you for the feedback

Your case is working already (if you don't use default logging)

Just start multiple brokers manually in one runtime:

```python
kafka_broker = KafkaBroker(...)
rabbit_broker = RabbitBroker(...)

@kafka_broker.publisher(...)
@rabbit_broker.subscriber(...)
async def handler(event: str) -> str:
    return event

@asynccontextmanager
async def lifespan():
    async with rabbit_broker:
        yielf

app = FastStream(kafka_broker, lifespan=lifespan)
```

We are working on native multiple brokers support, but it is the feature I plan on 1.0.0 version (end of this year I hope). I should close this issue as a copy of #526 , sorry

**Comment by yuyupopo** [comment]
Thank you for letting me know! Such a convenient framework. Didn't know it was possible.

**Comment by Lancetnik** [comment]
Publisher is just a protocol and all subscribers can run any publisher easely: https://github.com/airtai/faststream/blob/main/faststream/broker/subscriber/usecase.py#L352 (if you are insterested about details)

**Comment by chrisgoddard** [comment]
Ahhh! I've been looking for this!

One note though for anyone else - the global context variable "broker" is set in the initializer of the Broker abstract class (BrokerUseCase) - which means if you initialize two brokers, whichever one is initialized last will be the value of "broker" if you use a `Context` dependency injector to get it in a function somewhere - just a gotcha if you're doing this.
