### ISSUE TITLE
Bug: Pydantic Model is not fully defined. Possible bug in type resolver

### ISSUE THREAD

**Issue by yuyupopo** [airtai/faststream#1492]
**Describe the bug**

When I follow the [tutorial in the docs that uses pydantic model as serializer](https://faststream.airt.ai/latest/getting-started/subscription/pydantic/#pydanticbasemodel), I got an error. 

```python
`handle ` is not fully defined; you should define `UserInfo`, then call `handle.model_rebuild()`.
```

Instead of running the code as-is, I've splitted the app definition from the `handle` function definition.

**How to reproduce**

```python
# broker.py
from __future__ import annotations

from pydantic import BaseModel, Field, NonNegativeInt

from faststream.rabbit import RabbitBroker

broker = RabbitBroker("amqp://guest:guest@localhost:5672/")

class UserInfo(BaseModel):
    name: str = Field(
        ..., examples=["John"], description="Registered user name"
    )
    user_id: NonNegativeInt = Field(
        ..., examples=[1], description="Registered user id"
    )

@broker.subscriber("test-queue")
async def handle(
    user: UserInfo,
):
    assert user.name == "John"
    assert user.user_id == 1
```

```python
# app.py
from __future__ import annotations

from faststream import FastStream

from .broker import broker

app = FastStream(broker)
```

I've split the file that contains the `UserInfo` definition and the `app`
Also note the `from __future__ import annotations` at the top.
When the application actually receives a message, the error is raised.

**Additional context**
From what I understand, the `fast_depends` package tries to build a pydantic model for the `handle` function, but fails to resolve  `ForwardRef("UserInfo")`. 

I think this line is causing the problem.
https://github.com/Lancetnik/FastDepends/blob/a936df9f9c9fcfa91f3e0d628d9839bb1d01e343/fast_depends/utils.py#L83

If i change the line from `globalns = getattr(call, "__globals__", {})` to `globalns = sys.modules.get(call.__module__).__dict__`, app works as expected.

**Comment by Lancetnik** [comment]
Thank you for the report and for the way to fix it! I'll have a time to look into it at the end of week. It can be very helpful if you create the PR to FastDepends with fix (if you want to make the process a little bit faster)

**Comment by yuyupopo** [comment]
@Lancetnik I've created the PR. The fix is very straightforward, and I have wrote some explanation about the changes. Hope it helps. Best, if you can create another release after the merge.
