### ISSUE TITLE
Feature: Add a "ready" subcommand.

### ISSUE THREAD

**Issue by brunns** [airtai/faststream#1534]
**Is your feature request related to a problem? Please describe.**

I'm starting a containerised faststream application via a `docker-compose.yml` file, with some other services depending on the faststream application.

For all my other services, I'm able to define a health check, which I have found greatly improves the reliability of my tests.

Where it's easy to build http endpoints into our application, that's an obvious route to go, but several services instead include a cli command to confirm that the service is running and healthy - PostgreSQL's [`pg_isready`](https://www.postgresql.org/docs/current/app-pg-isready.html), for example, or MinIO's [`ready`](https://min.io/docs/minio/linux/reference/minio-mc/mc-ready.html). It would be great if faststream had such a command line subcommand.

**Describe the solution you'd like**

I cli subcommand, of the form `faststream ready app:app`, which would return a status code of zero if the service is up and running, and non-zero otherwise.

**Feature code example**

```shell
faststream ready app:app
```

**Comment by Lancetnik** [comment]
It is srtongly related to #1181 and we are already working on it. Can we close this Issue as a copy?

**Comment by brunns** [comment]
Absolutely, thanks.

Closed as duplicate of #1181.
