### ISSUE TITLE
Bug: RedisTelemetryMiddleware typing check fails

### ISSUE THREAD

**Issue by febus982** [airtai/faststream#1563]
**Describe the bug**
Typing check does fail when using OTEL middleware on RedisBroker

**How to reproduce**
Include source code:

```python
from faststream.broker.core.usecase import BrokerUsecase
from faststream.broker.publisher.proto import PublisherProto
from faststream.redis import RedisBroker
from faststream.redis.opentelemetry import RedisTelemetryMiddleware

def init_broker(config: AppConfig) -> BrokerUsecase[Any, Any]:
    broker = RedisBroker(
        config.EVENTS.REDIS_BROKER_URL,
        middlewares=(RedisTelemetryMiddleware,),
    )

    return broker
```

**Expected behavior**
`RedisTelemetryMiddleware` to match the typing specs defined at https://github.com/airtai/faststream/blob/4a2341d3b79f4cb6c780e82211145b2c12c6513f/faststream/redis/broker/broker.py#L134

**Observed behavior**
Mypy fails type checking

```
src/bootstrap/faststream.py:15: error: Argument "middlewares" to "RedisBroker" has incompatible type "tuple[type[RedisTelemetryMiddleware]]"; expected "Iterable[Callable[[PubSubMessage | DefaultListMessage | BatchListMessage | DefaultStreamMessage | BatchStreamMessage | None], BaseMiddleware]]"  [arg-type]
```

**Screenshots**
Not applicable

**Environment**
```
Running FastStream 0.5.14 with CPython 3.11.9 on Darwin
```

**Additional context**
N/A

**Comment by draincoder** [comment]
Hi! Your snippet does produce an error, but it's not a bug. The fact is that you need to initialize the middleware by passing parameters to it if necessary. Here is an [example from the documentation](https://faststream.airt.ai/latest/getting-started/opentelemetry/#faststream-tracing).

**Comment by febus982** [comment]
🤦‍♂️ Thanks for double-checking this
