### ISSUE TITLE
RequestValidationError handler when using NATS and FastAPI

### ISSUE THREAD

**Issue by rafi-rr** [airtai/faststream#1617]
I'm not sure if this is a bug or just a usage issue but I can't handle RequestValidationError when messages are invalid.

I tried the FastAPI approach as documented [here](https://fastapi.tiangolo.com/tutorial/handling-errors/#override-request-validation-exceptions) but the handler is never called even though RequestValidationError exception is raised and not handled except by FastAPI's logger, in our case.

Please assist.

**Comment by ShchekodinNA** [comment]
I agree. It's very annoying

**Comment by Lancetnik** [comment]
Sorry, missed this case. We can't use `fastapi.exception_handler` logic here, but we are working on **FastStream**-native way to process errors.

Now you can use our middlewares for it, but built-in mechanism should be released next week
