### ISSUE TITLE
Bug: When using `@subscriber` with `TopicPartition` and changing the `--workers` parameter - the event processing is duplicated

### ISSUE THREAD

**Issue by shepilov-vladislav** [airtai/faststream#1621]
**Describe the bug**
When using `@subscriber` with `TopicPartition` and changing the `--workers` parameter - the event processing is duplicated

**How to reproduce**
Include source code:

```python
from faststream import FastStream
from faststream.kafka import KafkaBroker, KafkaRouter, TopicPartition


broker_router = KafkaRouter()


@broker_router.subscriber(
    partitions=[TopicPartition("test-topic", 0)],
    group_id="my-group",
)
async def process_event(msg: dict):
    print(msg)


broker = KafkaBroker()
app = FastStream(broker)
broker.include_router(broker_router)
...
```

And/Or steps to reproduce the behavior:

1. Start with `--workers=2`
2. Send any event to `test-topic` 0 partition - it will be processed twice

**Expected behavior**
Event should be processed only 1 time

**Environment**
```shell
Running FastStream 0.5.14 with CPython 3.11.9 on Darwin
```

**Comment by spataphore1337** [comment]
Technically, there is no bug or problem. The point is that Kafka does the balancing between consumer instances by assigning each instance its own partition in the topic. However, you specify explicitly which partition to read, so each instance in your case reads exactly the partition it was specified to read.
