### ISSUE TITLE
Feature: High contrast documentation

### ISSUE THREAD

**Issue by chanpl** [airtai/faststream#1623]
**Is your feature request related to a problem? Please describe.**
faststream home page and documentation is hard to read for vision imparied.

**Describe the solution you'd like**
Make the home page and docs more easy to read for vision impaired, like the FastAPI docs. Perhaps a button to switch to high contrast doc is desirable for some people.

**Describe alternatives you've considered**
I think a simple solution like having high contrast background + text is good enough.

**Comment by kumaranvpl** [comment]
Hello @chanpl,

Sorry for your bad experience with faststream homepage. We will work on providing a better reading experience in the homepage. 

We do provide darkmode and lightmode in faststream docs similar to fastapi docs
![Screenshot from 2024-07-29 11-56-20](https://github.com/user-attachments/assets/b64aab18-0d32-40d3-b68c-457b50a45506)
![Screenshot from 2024-07-29 11-56-27](https://github.com/user-attachments/assets/fc65a201-b612-410a-a8d9-d1c996687aef)

Below are the darkmode and lightmode from fastapi docs
![Screenshot from 2024-07-29 11-56-02](https://github.com/user-attachments/assets/54c14461-a7f3-4ce3-8914-dc5e06cfdd16)
![Screenshot from 2024-07-29 11-56-10](https://github.com/user-attachments/assets/469cc458-bb33-483e-a180-442ab7d398ea)

Are you okay with our darkmode and lightmode implementation? Or do you like to have somethine else? Please let us know @chanpl

**Comment by chanpl** [comment]
@kumaranvpl Thank you very much for your positive response. The dark mode looks good to me :-) While the home page can be improved, but it's not a high priority.

**Comment by Lancetnik** [comment]
I think we can close the Issue due it doesn't related to **FastStream** itself, but landing styling

**Comment by kumaranvpl** [comment]
@Lancetnik Yep, we are not going to add dark/light styling for landing page anytime soon. The actual docs has dark/light theming for accessibility purposes. I think that is enough for now.
