### ISSUE TITLE
Fix: need to speed up testing for confluent

### ISSUE THREAD

**Issue by Flosckow** [airtai/faststream#1638]
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
Slow running tests for confluent

**Describe the solution you'd like**
Significantly speed up test execution.

**Comment by Lancetnik** [comment]
Finally, I found the problem - confluent-kafka takes a lot of time at broker starting dur automatic partition assignment:

So, for this code the first message will be consumed after about 3 seconds after startup

```python
consumer.subscribe(["test-in",])

while True:
    msg = consumer.poll(timeout=0.1)
```

But, in the next case the message will be delivired immideately

```python
consumer.assign([TopicPartition(topic="test-in", partition=0, offset=0)])

while True:
    msg = consumer.poll(timeout=0.1)
```

I think, we should use manual partition assignment for aiokafka and confluent kafka both in tests this reason

@kumaranvpl what do you think? Have you any other solutions?

* [ ] refactor tests to provide custom args, kwargs to broker.subscriber test
* [ ] impl manual TopicPartition assignment for confluent
