### ISSUE TITLE
Can not proper handle long running task

### ISSUE THREAD

**Issue by alteest** [airtai/faststream#1639]
**Describe the bug**
Handle long running task.
When I need to run synchronous long running task RabbitMQ server just close connection and then impossible to acknowledge it (at the end of processing)

**How to reproduce**
Include source code:

```python
from faststream import FastStream

broker = RabbitBroker('amqp://...')
app = FastStream(broker=broker)

@broker.subscriber('default', no_ack=True)
def on_message(body, logger: Logger, message: RabbitMessage):
    logger.info(f'Receive message : {body}')
    time.sleep(1000)
    message.ack()
```

**Expected behavior**
I want to keep connection open and want that FastStream send heartbeat message

**Observed behavior**
RabbitMQ server close connection because don't receive heartbeat message

**Additional context**
There is a solution with raw pika: https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py
But here in FastStream consumer I don't have channel and connection to proper handle it in dedicated thread.
For now I use pika and it works just fine, but I would like to have such possibility inside FastStream to use this framework

**Comment by Lancetnik** [comment]
@alteest hi, thank you for the report!
Regular `def ...` function is running in thread-pool, so it can't block healthcheck.
Btw, `message.ack()` is an async function and u can't run it in the sync code, use regular **FastStream** acknowledgement logic or status exceptions instead.
Also, can you provide your error log to show me the problem?

**Comment by alteest** [comment]
Yes, I saw that regular functions is running in thread-pool
Ok. But I want to acknowledge message after processing.
Actually, no errors, just message return back to queue due to heartbeat (and connection) loss on server side. And disable heartbeats is not a solution

**Comment by Lancetnik** [comment]
Did you check this Issue: https://github.com/airtai/faststream/issues/1636

Probably, you have small `consumer_timeout`?

**Comment by alteest** [comment]
Updated my test case. Work as expected.
Sorry for false alarm
