### ISSUE TITLE
Bug: Cant obtain an AsyncAPIDefaultSubscriber object, when using Kafka and FastAPI

### ISSUE THREAD

**Issue by JohannT9527** [airtai/faststream#1640]
**Describe the bug**

The subscriber method of the KafkaRouter class is annotated with the return type AsyncAPIDefaultSubscriber, but the actual return type is function. 

**How to reproduce**
Include source code:

```python
from fastapi import FastAPI
from faststream.kafka.fastapi import KafkaRouter


router = KafkaRouter()

subscriber = router.subscriber('test_in')
print(f'real type is {type(subscriber)}')


app = FastAPI(lifespan=router.lifespan_context)
app.include_router(router)
```

And/Or steps to reproduce the behavior:

Execute the above code

**Comment by Lancetnik** [comment]
Sorry, I just didn't refactored **FastAPI** integration since 0.5.0 release yet. We should make it the same with regular `router.subscriber()` behavior
