### ISSUE TITLE
Feature: RabbitMQ add support for fail_fast param

### ISSUE THREAD

**Issue by gaby** [airtai/faststream#1647]
Currently the RabbitMQ broker is based on a RobustConnection from aio-pika.

The options available with the broker although plenty are missing a few important ones. One of the is "fail_fast" param. This param allows you to start your code even if RabbitMQ is down, else it will fail after a timeout.

Example of using this with aio-pika

```python
connection = RobustConnection(RABBITMQ_URL, fail_fast="False")
await connection.connect()
```

Yes, the param is a `string`. Probably makes sense to make it a Boolean on `faststream` side. By default `fail_fast` is enabled.

**Comment by Lancetnik** [comment]
Thank you for the notice! I added `fail_fast` and `reconnect_interval` options
Am I missed smth else?

**Comment by gaby** [comment]
@Lancetnik That was fast! Thank you! 💪
