### ISSUE TITLE
Bug: subscriber's `retry` doesn't work and cause infinity message nacking.

### ISSUE THREAD

**Issue by RoTorEx** [airtai/faststream#1657]
**Describe the bug**
Faststream[Rabbit] on version 5.17 subscriber's param `retry` gather than 0 cause infinity retrying.

**How to reproduce**
Include source code:

```python
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from faststream import Logger
from faststream.rabbit import RabbitBroker, RabbitMessage, RabbitQueue
from faststream.exceptions import NackMessage


rabbit_broker = RabbitBroker("amqp://dev:1234@localhost:5672")


@asynccontextmanager
async def custom_lifespan(_: FastAPI) -> AsyncGenerator[None, Any]:
    await rabbit_broker.start()
    yield


app = FastAPI(lifespan=custom_lifespan)


RETRY = 1  # !Change me :D


async def bug_consumer(msg: RabbitMessage, logger: Logger) -> None:
    logger.info("Received a message with ID `%s` from `bug.q` queue with body `%s`.", msg.message_id, msg.decoded_body)

    # await msg.nack()  # !When `RETRY = 0`, broker starts infinity loop without message counting in `CounterWatcher`.

    # raise NackMessage  # !If `RETRY = 0`, works fine? But if `RETRY = 1`, `CounterWatcher` doesn't count tries on right way and broker starts ping-pong (nacking) message.
    # raise ValueError("1 + 1 != 3")  # !Same here.


rabbit_broker.subscriber(queue=RabbitQueue("bug.q", durable=False), retry=RETRY)(bug_consumer)
```

And/Or steps to reproduce the behavior:

1. Install depends
2. `poetry run uvicorn bug:app --host 0.0.0.0 --port 80 --reload`
3. Uncomment one line (17-19)
4. Open RabbitMQ and publish message into `bug.q`

**Expected behavior**
I guess `retry` param in should affect how many times massage was processed and stop trying to handle it retry count is reached.

**Observed behavior**
As I see each nack return message back in the queue with different ID. That's why `CounterWatcher` class increase amount of messages in `self.memory` creating a new object in memory during each try. It cause memory leaking to.

**Screenshots**
<img width="1251" alt="Screenshot 2024-08-09 at 13 49 47" src="https://github.com/user-attachments/assets/b5b11df9-9e3d-4652-b263-0e8a9dec7161">

**Environment**
Running FastStream 0.5.17 with CPython 3.12.4 on Darwin

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by Lancetnik** [comment]
@RoTorEx thank you for the report! But can you take a look here, please: https://github.com/airtai/faststream/issues/1603 ?
Is your problem the same?

**Comment by RoTorEx** [comment]
Hey, @Lancetnik.

It seems like this ticket describes the same problem. Also I didn't see any cautions in the documentation. Could you explain please how I need to manage some publisher settings with `massage_id` so that `retry` begin to work?

**Comment by Lancetnik** [comment]
> Hey, @Lancetnik.
> 
> It seems like this ticket describes the same problem. Also I didn't see any cautions in the documentation. Could you explain please how I need to manage some publisher settings with `massage_id` so that `retry` begin to work?

If you publishes the message via **FastStream** or **aio-pika** they setts message id automatically. Which tool are you using? Anyway, it should has the same parameter in the signature

**Comment by RoTorEx** [comment]
My service receive messages from remote hosts via RabbitMQ Shovels :)

**Comment by Lancetnik** [comment]
> RabbitMQ Shovels

Sorry, but I am not familiar with this plugin. I can suggest you just do not use `retry` feature and call `message.ack/nack` manually. Anyway, I am planning to deprecate this option and remove it in 0.6.0

**Comment by RoTorEx** [comment]
Got it. Thanks a lot for your answers.

**Comment by Lancetnik** [comment]
You're welcome. Can we close the Issue on this?

**Comment by RoTorEx** [comment]
Yeap :)

**Comment by dearkafka** [comment]
well, how can we re-implement retries through nack/ack properly when it will be deprecated? @Lancetnik how can we keep track of retry number?

**Comment by Lancetnik** [comment]
> well, how can we re-implement retries through nack/ack properly when it will be deprecated? @Lancetnik how can we keep track of retry number?

In the way you want: in-memory / redis / using message properties

The current implementation promises smth, but can't guarantee anything. Also, I can't make it better due our ideology - we can't make service statefull or use external storage. So, I want to remove "retry" option and replace it by `on_error=AckPolicy.nack/reject/do_nothing` or smth like that

**Comment by dearkafka** [comment]
yeah, ok. but leaving my 5 cents: it's actually handy that it's possible to do retry=2  e.g. in my case for some unclear reason it happens that I receive AMQPConnectionError (maybe network itself is buggy) and so I just need a second try. actually this AMQPConnectionError is quite bothering, I feel like its possible to do re-connect at pika level but not on faststream

**Comment by Lancetnik** [comment]
> yeah, ok. but leaving my 5 cents: it's actually handy that it's possible to do retry=2 e.g. in my case for some unclear reason it happens from time to time that I receive AMQPConnectionError (maybe network itself is buggy) and so I just need a second try. actually this AMQPConnectionError is quite bothering, I feel like its possible to do re-connect at pika level but not on faststream

Probably your connection errors can be fixed by `max_consumers` (qos) parameter usage. It's some kind of magic I found

**Comment by dearkafka** [comment]
> > yeah, ok. but leaving my 5 cents: it's actually handy that it's possible to do retry=2 e.g. in my case for some unclear reason it happens from time to time that I receive AMQPConnectionError (maybe network itself is buggy) and so I just need a second try. actually this AMQPConnectionError is quite bothering, I feel like its possible to do re-connect at pika level but not on faststream
> 
> Probably your connection errors can be fixed by `max_consumers` (qos) parameter usage. It's some kind of magic I found

its like consumer_max_per_channel?

**Comment by Lancetnik** [comment]
> its like consumer_max_per_channel?

Yes
