### ISSUE TITLE
Feature: disable auto topic creation in Confluent FastAPI KafkaRouter

### ISSUE THREAD

**Issue by ronfarkash** [airtai/faststream#1658]
To suggest an idea or inquire about a new Message Broker supporting feature or any other enhancement, please follow this template:

**Is your feature request related to a problem? Please describe.**
I am using FastStream Confluent KafkaRouter in a Kafka cluster where the users are not authorized to create topics, I know that creating a Confluent KafkaBroker allows to disable this feature, but the KafkaRouter does not recognize this argument.

**Describe the solution you'd like**
Allow to control this feature in KafkaRouter as well

**Feature code example**
To help others understand the proposed feature, illustrate it with a **FastStream** code example:

```python
from faststream import FastStream
from faststream.confluent.fastapi import KafkaRouter
from faststream.confluent import KafkaBroker

# this is not implemented yet
kafka_router = KafkaRouter(..., allow_auto_topic_creation=False)

# this is implemented
kafka_broker = KafkaBroker(..., allow_auto_topic_creation=False)
```

**Describe alternatives you've considered**
I just have 4 warnings every time I run my code

**Additional context**
I don't think any additional context is required.

Thank you very much!

**Comment by Lancetnik** [comment]
Sorry, that is the FastAPI integration, missed that

**Comment by Lancetnik** [comment]
@ronfarkash I don't know, how we missed that, sorry... 
Can I ask you to try the next thing by yourself: please, copy `allow_auto_create_topics` from the broker signature to FastAPI Router init and pass it to [`super().__init__(allow_auto_create_topics=allow_auto_create_topics)`](https://github.com/airtai/faststream/blob/main/faststream/confluent/fastapi/fastapi.py#L368)?

It should helps. This case u can just create a PR to FastStream and I merge it instantly

I just can't fix it due I am afk next few days
