### ISSUE TITLE
Feature: Support for AMQP Exchange Type X_DELAYED_MESSAGE in FastAPI Integration

### ISSUE THREAD

**Issue by JokaHD** [airtai/faststream#1668]
The `ExchangeType.X_DELAYED_MESSAGE` is not supported when using FastStream with FastAPI. It works with the FastStream CLI but fails with the FastAPI CLI due to missing support in the AMQP bindings.

Worked case (run with `faststream run main:app`):

```python
from faststream import FastStream
from faststream.rabbit import ExchangeType, RabbitBroker, RabbitExchange

broker = RabbitBroker("ampq://guest:guest@localhost:5672")
app = FastStream(broker)



deplayed_exchange = RabbitExchange(
    "deplayed_exchange",
    type=ExchangeType.X_DELAYED_MESSAGE,
    arguments={"x-delayed-type": "direct"},
)


@broker.subscriber("delayed_task", exchange=deplayed_exchange)
def task():
    pass

```

Failed worked case (run with `uvicorn main:app`):

```python
from fastapi import FastAPI
from faststream.rabbit import ExchangeType, RabbitExchange
from faststream.rabbit.fastapi import RabbitRouter

router = RabbitRouter("amqp://guest:guest@localhost:5672/")
app = FastAPI(lifespan=router.lifespan_context)
app.include_router(router)

deplayed_exchange = RabbitExchange(
    "deplayed_exchange",
    type=ExchangeType.X_DELAYED_MESSAGE,
    arguments={"x-delayed-type": "direct"},
)


@router.subscriber("delayed_task", exchange=deplayed_exchange)
def task():
    pass
```

This issue seems caused by the unsupported ExchangeType.X_DELAYED_MESSAGE here.
https://github.com/airtai/faststream/blob/main/faststream/asyncapi/schema/bindings/amqp.py#L41

**Describe the solution you'd like**
Add  `x-delayed-message` to https://github.com/airtai/faststream/blob/main/faststream/asyncapi/schema/bindings/amqp.py#L41
```python
type: Literal["default", "direct", "topic", "fanout", "headers", "x-delayed-message"]
```

**Additional context**
faststream==0.5.17

I'm not entirely sure if I'm using it incorrectly, or if there might be a specific reason why this exchange type isn't supported.
I'd appreciate any insights or clarification on this matter. Thank you for your time and consideration.

**Comment by Lancetnik** [comment]
Thank you for the report! Indeed, we should use the same ExchangeType enum in AsyncAPI too
