### ISSUE TITLE
Check taskiq integration

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#1701]
https://discord.com/channels/1085457301214855171/1085457302280228898/1275134622484795415

**Comment by kumaranvpl** [comment]
We can confirm that the `taskiq` integration is broken because taskiq changed its api since version `0.11.0`. 
A new issue is created at `taskiq-faststream` repo https://github.com/taskiq-python/taskiq-faststream/issues/68.

Temporary fix for this issue is to install slightly older version of taskiq by running the command `pip install taskiq==0.11.0`.

**Comment by Lancetnik** [comment]
I think, I'll solve it as taskiq-faststream Issue. Already have a decision, just need to merge

**Comment by kumaranvpl** [comment]
> I think, I'll solve it as taskiq-faststream Issue. Already have a decision, just need to merge

For future reference, taskiq integration has been fixed by @Lancetnik at `taskiq-faststream` repo and he made a new release - https://github.com/taskiq-python/taskiq-faststream/releases/tag/0.2.0. Now `taskiq-faststream` works with new version of `taskiq` as informed here - https://discord.com/channels/1085457301214855171/1085457302280228898/1276033190729093130
