### ISSUE TITLE
Test all faststream brokers using python3.13

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#1706]

**Comment by kumaranvpl** [comment]
Hello @Lancetnik, 

Here are my observations while trying to run FastStream tests using python3.13.

When I tried to install all the packages by running the command `pip install -e ".[dev]"`, `confluent-kafka-python` installation failed. This indicates that the `confluent-kafka-python` is not yet supported in python3.13. I have created an issue for this in `confluent-kafka-python` repository - https://github.com/confluentinc/confluent-kafka-python/issues/1802.

Then, I have installed everything except `faststream[confluent]`.

I ran CI tests in local using python3.13 to figure out which parts are working and which are not working. Following are the results:

**test-basic (3.13, pydantic-v1):**
`tests/a_docs/getting_started/asyncapi/asyncapi_customization/test_handler.py::test_handler_customization` is failing. But it is a simple formatting issue. Easy to fix.

**test-basic (3.13, pydantic-v2):** Same issue as test-basic (3.13, pydantic-v1)

**test-orjson:** Same issue as test-basic (3.13, pydantic-v1)

**test-kafka-smoke:** Everything passed

**test-confluent-smoke:** Failure because unable to install `confluent-kafka-python` using python3.13

**test-rabbit-smoke:** Everything passed

**test-nats-smoke:** Everything passed

**test-redis-smoke:** Everything passed

**test-kafka-real:** Everything passed

**test-confluent-real:** Failure because unable to install `confluent-kafka-python` using python3.13

**test-rabbit-real:** Everything passed

**test-nats-real:** Everything passed

**test-redis-real:** Everything passed

**Comment by Lancetnik** [comment]
@kumaranvpl thank you for the investigation  lot! Seems like we will wait for confluent-only again

**Comment by Lancetnik** [comment]
UPD: seems like they are working on 3.13 support already

https://github.com/confluentinc/confluent-kafka-python/issues/1768

**Comment by kumaranvpl** [comment]
> UPD: seems like they are working on 3.13 support already
> 
> [confluentinc/confluent-kafka-python#1768](https://github.com/confluentinc/confluent-kafka-python/issues/1768)

Good to know. I didn't search for past issues so I didn't came across the old issue. Looks like last reply was from June. I highly doubt that they are actively working on adding support for python3.13.
I would say adding new issue is good since they would be aware that multiple people are looking for python 3.13 support
