### ISSUE TITLE
Fix failing test in python3.13 - tests/a_docs/getting_started/asyncapi/asyncapi_customization/test_handler.py::test_handler_customization

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#1716]
As mentioned at https://github.com/airtai/faststream/issues/1706#issuecomment-2301340566, `tests/a_docs/getting_started/asyncapi/asyncapi_customization/test_handler.py::test_handler_customization` test is failing in python3.13. 
Fix the test and make it pass to support python3.13.

**Comment by Lancetnik** [comment]
@kumaranvpl I think, it is the time to fix it. 3.13 should be released soon

**Comment by kumaranvpl** [comment]
> @kumaranvpl I think, it is the time to fix it. 3.13 should be released soon

I know. Already had it in mind since last week but not enough time as I was working on different things.
I will start working on this next week.
