### ISSUE TITLE
Bug: Missing typer dependency

### ISSUE THREAD

**Issue by hemker** [airtai/faststream#1784]
**Describe the bug**
Faststream is missing its `typer` dependency. Installing `faststream` in a fresh environment does not pull in `typer`, but `faststream` expects it to be present.

**How to reproduce**
```
pip install --upgrade faststream[rabbit]
faststream --help
```
or any other faststream command call.

**Expected behavior**
I expect the dependencies to be set correctly so a `pip install faststream[rabbit]` runs in a fresh environment.

**Observed behavior**
I need to manually install `typer`.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**
Not working though.

**Comment by Lancetnik** [comment]
Please, read latest release announce. I published it everywhere, but seems like you missed it, sorry
We moved **typer** to special `faststream[cli]` distribution and default installation doesn't requre it anymore
https://github.com/airtai/faststream/releases/tag/0.5.23
I can just add correct ImportError message for such case

**Comment by hemker** [comment]
Ah thanks, I see. I indeed missed that, not expecting such a change in a patch release. Anyways, highly appreciate a better import error message. Another question is, if everything related to `cli` is moved to the dedicated ``faststream[cli]` package, why is the `faststream` wrapper script still shipped with the regular `faststream` installation?

**Comment by Lancetnik** [comment]
> why is the `faststream` wrapper script still shipped with the regular `faststream` installation?

There is no special script - it just a package itself. Split it to separated packages makes things too complex, so I preffered to move useless for default distribution dependencies to a new extra
