### ISSUE TITLE
Bug: Injecting a custom Context field implementing __eq__ does not work

### ISSUE THREAD

**Issue by antoinehumbert** [airtai/faststream#1806]
**Describe the bug**
Since https://github.com/airtai/faststream/pull/1667/files, when trying to use a custom Context field that implements \_\_eq\_\_ returning `NotImplemented` in some cases, the dependency is not injected in subscriber.

**How to reproduce**
Having following User class:

```python
class User:
    def __init__(self, id):
        self.id = id

    def __eq__(self, other):
        if not isinstance(other, User):
            return NotImplemented
        return self.id == other.id
```

Having a middleware injecting a User object in the context:

```python
from faststream import BaseMiddleware, context


class UserMiddleware(BaseMiddleware):
    async def on_consume(self, msg):
        context.set_local("user", User(1))
        return await super().on_consume(msg)
```

Having a subscriber with `user` from context as a dependency:

```python
@broker.subscriber("authenticated-topic")
def handler(msg, user: User = Context("user")):
    ...
````

The `user` parameter is not injected leading to a pydantic validation error because field is missing.

The issue arises because this (https://github.com/airtai/faststream/blob/689f6740a67c19b70c1e488afa081fe7a5b02eb2/faststream/utils/context/types.py#L63) `if` statement always evaluates to `False`.

Here is what happens when doing the comparison with `EMPTY`:

* `User.__eq__` is called, returning `NotImplementError`
* So, the comparison `User(1) != EMPTY` evaluates to `not(NotImplementedError)` which is `False`, leading to not injecting `user` in kwargs.

I think that `_EmptyPlaceHolder.__eq__` should return `False` instead of `NotImplementedError` when compared with an object which is not an `_EmptyPlaceHolder` object, because this kind of comparison is what would most commonly happen at https://github.com/airtai/faststream/blob/689f6740a67c19b70c1e488afa081fe7a5b02eb2/faststream/utils/context/types.py#L63, and the fact is that any object that is not an `_EmptyPlaceHolder` instance should pass the test.

Additionaly, I think this comparison should be made with `EMPTY` as the lhs operand (i.e. `EMPTY != ...`), as this will ensure that `_EmptyPlaceHolder.__eq__` is called first and will always return a result (`True` if the rhs is an `_EmptyPlaceHolder` object, `False` otherwise), avoiding potential side effects depending on implementation of `__eq__` in the compared object

**Comment by Lancetnik** [comment]
@antoinehumbert thank you for such detail Issue! Do you want to make a PR (I see you almost have a fix) or let me do it by myself?

**Comment by antoinehumbert** [comment]
I'll provide a PR soon

**Comment by Lancetnik** [comment]
Thank you a lot!
