### ISSUE TITLE
Feature: Not update/create NATS streams/consumers

### ISSUE THREAD

**Issue by mkramb** [airtai/faststream#1830]
Hi, we are using NATS together with their k8s operator NACK which is used to provision stream & consumers (durable). Is there a way to disable create / updating of streams & consumers, and just rely them being provision by IAC. I haven't found this option, looking at example & docs, but I think it's  a common use-case. Would also be willing to contribute, but any feedback & guidance would be helpful.

Thanks,
Mitja

**Comment by Lancetnik** [comment]
Hi! Seems like you are looking for [`declare`](https://github.com/airtai/faststream/blob/main/faststream/nats/schemas/js_stream.py#L185) option - it is a common way to disable objects autocreation in **FastStream*8

**Comment by mkramb** [comment]
That works perfectly, which would prevent stream to be created, and for consumer I'm using durable, 
which would prevent to be created (I think), meaning in the end looks something like:

```
router = NatsRouter(NATS_URL, logger=logger)
stream = JStream(name="allocation", declare=False)

@router.subscriber(
    stream=stream,
    durable="processor-ready",
    subject="events.ready_to_process.*",
    pull_sub=PullSub(),
)
async def handleAllocationReady(event: AllocationReadyToProcess, msg: NatsMessage):
    logger.info("do the work")
    await msg.ack()
```

Thanks so much!
