### ISSUE TITLE
Feature: Add support for async deserializer

### ISSUE THREAD

**Issue by akolenko-tcs** [airtai/faststream#1833]
Hello again! I've decided to reopen the issue https://github.com/airtai/faststream/issues/1820. I didn't ask for adding avro code to your library, I just wanted to suggest adding support for async deserializers. 

In the example of faststream deserialization (https://faststream.airt.ai/latest/getting-started/serialization/examples/#avro) you have `msg_dict = fastavro.schemaless_reader(bytes_reader, schema)`. However, in the example I've provided in that issue was `writer_schema = await self._schema_registry.get_by_id(schema_id)`. So async deserialization would be really useful for using your library. 

Hope that you understood what I've meant. If you have any questions, feel free to ask them.

**Comment by Lancetnik** [comment]
"Reopen Issue" is not the same with "create a new one"

Also, I still can't get your idea. You refer to not-FastStream code (avro serialization), so I don't think, that we can/should improve it

Can you suggest any **API** to explain me how it should works?

**Comment by Lancetnik** [comment]
Probably, your Issue related to #1774

**Comment by Lancetnik** [comment]
@kumaranvpl can you help me here, please?

**Comment by aKardasz** [comment]
@akolenko-tcs this wouldn't be a feature faststream adds because faststream is built to not be batteries included, if you want an async deserializer you would write and maintain it in your own codebase as an extension so to speak of this library and use it instead of the default one provided.

**Comment by Lancetnik** [comment]
Sorry, but I have to close the Issue due it doesn't related to **FastStream**
