### ISSUE TITLE
Bug: calls piling up during tests with dynamic subscription

### ISSUE THREAD

**Issue by Nnonexistent** [airtai/faststream#1872]
**Describe the bug**
Conditions:
* Dynamic subscription (see the code), for example during lifespan or on_startup event.
* Creating a testing context for every test, not only once per test run

In that case the subscribers will accumulate calls, that will dramatically reduce the execution time, giving high number of tests.

**How to reproduce**
Minimal reproducible example:
```python
from contextlib import asynccontextmanager

import pytest
from faststream import FastStream, TestApp
from faststream.rabbit import RabbitBroker, TestRabbitBroker

broker = RabbitBroker("amqp://guest:guest@localhost:5672/")


@asynccontextmanager
async def registration_lifespan():
    @broker.subscriber("test-queue")
    async def handle(name: str, user_id: int):
        pass

    yield

    # Uncomment this to make tests pass, a workaround
    # broker._subscribers.clear()


app = FastStream(broker, lifespan=registration_lifespan)


@pytest.fixture(autouse=True)
async def _setup_broker_for_test():
    async with TestRabbitBroker(broker), TestApp(app):
        yield


@pytest.mark.asyncio
async def test_handle_1():
    await broker.publish({"name": "John", "user_id": 1}, queue="test-queue")

    subscriber = next(iter(broker._subscribers.values()))
    assert len(subscriber.calls) == 1


@pytest.mark.asyncio
async def test_handle_2():
    await broker.publish({"name": "John", "user_id": 1}, queue="test-queue")

    subscriber = next(iter(broker._subscribers.values()))
    assert len(subscriber.calls) == 1  # Will fail here, `broker._subscribers` will have 2 calls
```

**Expected behavior**
No calls duplication.

I've expected that either `broker.close` (or at least `TestBroker.__aexit__`) would clear the subscriptions.
Or subscription process would handle repetition (which could be hard in the dynamic use case).

**Observed behavior**
Subscriptions are not cleared after application or broker end of life.

**Environment**
Running FastStream 0.5.25 with CPython 3.11.3 on Linux

**Additional context**
In my case I need to call `TestBroker` for every test, because I need to isolate the event loop on the function level. So I couldn't use `scope="session"`, unfortunately.

**Comment by Lancetnik** [comment]
Looks like a copy of #1036

**Comment by Nnonexistent** [comment]
Yes seems like it, thanks. I hope it'll be solved at some point.

I did run a search, but I've missed that ticket.
