### ISSUE TITLE
Feat: add warning for NATS subscriber factory if user sets useless options

### ISSUE THREAD

**Issue by HHongSeungWoo** [airtai/faststream#1899]
**Describe the bug**
The extra_options parameter is not utilized when using pull_subscribe in nats.

Below is the function signature from natspy
```    python
async def subscribe(
        self,
        subject: str,
        queue: Optional[str] = None,
        cb: Optional[Callback] = None,
        durable: Optional[str] = None,
        stream: Optional[str] = None,
        config: Optional[api.ConsumerConfig] = None,
        manual_ack: bool = False,
        ordered_consumer: bool = False,
        idle_heartbeat: Optional[float] = None,
        flow_control: bool = False,
        pending_msgs_limit: int = DEFAULT_JS_SUB_PENDING_MSGS_LIMIT,
        pending_bytes_limit: int = DEFAULT_JS_SUB_PENDING_BYTES_LIMIT,
        deliver_policy: Optional[api.DeliverPolicy] = None,
        headers_only: Optional[bool] = None,
        inactive_threshold: Optional[float] = None,
    ) -> PushSubscription:
    
  async def pull_subscribe(
      self,
      subject: str,
      durable: Optional[str] = None,
      stream: Optional[str] = None,
      config: Optional[api.ConsumerConfig] = None,
      pending_msgs_limit: int = DEFAULT_JS_SUB_PENDING_MSGS_LIMIT,
      pending_bytes_limit: int = DEFAULT_JS_SUB_PENDING_BYTES_LIMIT,
      inbox_prefix: bytes = api.INBOX_PREFIX,
  ) -> JetStreamContext.PullSubscription:
```

**How to reproduce**
```python
import asyncio

from faststream import FastStream
from faststream.nats import PullSub, NatsBroker
from nats.js.api import DeliverPolicy


broker = NatsBroker()
app = FastStream(broker)


@broker.subscriber(subject="test", deliver_policy=DeliverPolicy.LAST, stream="test", pull_sub=PullSub())
async def handle_msg(msg: str): ...


if __name__ == "__main__":
    asyncio.run(app.run())

```

**Comment by Lancetnik** [comment]
Sorry, but I don't know, what you mean. You sets deliver policy, that has no sence for PullSubscriber and we just do not use this option.

Here is parameters parsing logic

https://github.com/airtai/faststream/blob/main/faststream/nats/subscriber/factory.py#L94

The only one way to help you - just add warning for useless parameters if they set (like we do for `max_workers` option). And we are working on it already

**Comment by Lancetnik** [comment]
@sheldygg can you help me with it, please?

**Comment by HHongSeungWoo** [comment]
First of all, thank you for creating such an amazing library! :+1: 

Looking at https://github.com/airtai/faststream/blob/3cca7f8dadcfb097ef7eaa783f5037e2028ebee3/faststream/nats/subscriber/usecase.py#L836
it appears that extra_options is passed to the pull_subscribe function. However, users expect the deliver_policy to apply when set as a parameter in broker.subscriber, but since pull_subscribe does not include a deliver_policy parameter, it isn’t applied.

How about merging extra_options with config before passing it?

**Comment by Lancetnik** [comment]
@HHongSeungWoo indeed, you are right, I found it in **nats-py** source. Seems like, we should create Config object inside factory and merge most options to it
