### ISSUE TITLE
Bug: CLI is incompatible with structlog

### ISSUE THREAD

**Issue by pySilver** [airtai/faststream#1900]
**Describe the bug**
There is inconsistent behavior when using `structlog` as described at https://faststream.airt.ai/latest/getting-started/logging/?h=structlog#structlog-example 

When app is executed as `python my_app.py` and logger is configured as `logger = structlog.get_logger()` we will get consistent formatting and all other benefits of using `structlog`. However this way we will lose benefits of using `faststream cli`, such as controllable log-level, realoads, workers etc.

On the other hand, when using `faststream cli` with logger configured as `logger = structlog.get_logger()` we will not be able to control log level as in that case checks within `faststream.cli.utils.logs.set_log_level` will fail: https://github.com/airtai/faststream/blob/fc61e913cea6d09b25524141af7272496606a20f/faststream/cli/utils/logs.py#L67 as structlog's `BoundLogger` has no such method as `setLevel`. 

**Solution**
I don't have a good solution for that. We may want to modify `set_log_level` function so it will check if logger is some other type than `logging.Logger` and call `logging.getLogger().setLeveL(level)` to configure root logger level. But that might not be a perfect solution I suppose.

**Comment by pySilver** [comment]
alternatively CLI might set env `FASTSTREAM_LOG_LEVEL` variable so app can handle it manually when needed

**Comment by Lancetnik** [comment]
It doesn't look as **FastStream** problem for me, please open an Issue to **structlog** itself to add `setLevel` method for regular **logging** compatibility
