### ISSUE TITLE
Bug: with multiple handlers  only the first is triggered

### ISSUE THREAD

**Issue by baterflyrity** [airtai/faststream#1901]
**Describe the bug**
* RabbitMQ broker
* Several handlers decorated with single subscriber
* Only the first handler is triggered and logged

**Expected behavior**
* handler1 is called
* handler2 is called

**Observed behavior**
* handler1 is called
* handler2 is **not** called

**Screenshots**

![image](https://github.com/user-attachments/assets/73804bbb-5dc0-4d3d-8f67-0156c5f864a3)

**Environment**
lol, `ModuleNotFoundError: No module named 'typer'`

**Comment by Lancetnik** [comment]
Sorry, but it doesn't work this way
Using shared subscriber you overload it by filters - https://faststream.airt.ai/latest/getting-started/subscription/filtering/

**Comment by baterflyrity** [comment]
Thanks.
This behavior definitely should be stated somewhere in features/tutorial.

**Comment by Lancetnik** [comment]
> Thanks. This behavior definitely should be stated somewhere in features/tutorial.

I think "filtering" documentation page is enough, isn't it? I have no ideas about additinal places to show the hint
Anyway, if know the correct place, feel free to make a PR - I'll be happy to merge documentation improvements
