### ISSUE TITLE
Feature: @rabbit_router.publisher ignore None message

### ISSUE THREAD

**Issue by 781574155** [airtai/faststream#1941]
here is my code.
```python
@rabbit_router.subscriber(queue=RabbitQueue(name='tmp-q-embeddings', exclusive=True), exchange=md_exch)
@rabbit_router.publisher(queue=file_process_finish_queue)
async def on_user_file_upload(ufu: IntermediateFileUploadMessage):
    return await md_file_upload_embeddings_callback(rabbit_router.broker, ufu)
```
if md_file_upload_embeddings_callback function return None，there will be  an empty message sended to the rabbitmq.
I want not send any message on None return value.

**Comment by kumaranvpl** [comment]
Hello @781574155,

FastStream provides multiple ways to publish a message. Why don't you try the following approach?

```python
@rabbit_router.subscriber(queue=RabbitQueue(name='tmp-q-embeddings', exclusive=True), exchange=md_exch)
@rabbit_router.publisher(queue=file_process_finish_queue)
async def on_user_file_upload(ufu: IntermediateFileUploadMessage):
    msg = await md_file_upload_embeddings_callback(rabbit_router.broker, ufu)
    if msg is not None:
        rabbit_router.publish(msg, queue=file_process_finish_queue)
```

This is taken from our documentation - https://faststream.airt.ai/latest/rabbit/publishing/#rabbit-publishing

**Comment by 781574155** [comment]
@kumaranvpl Thank you for your reply. your answer can solve the problem.
But I still think you guys should add support for None return value to not send any message.
The README.md says
`These decorators make it easy to specify the processing logic for your consumers and producers, allowing you to focus on the core business logic of your application without worrying about the underlying integration.`
that's why I insist to add support

**Comment by kumaranvpl** [comment]
Helo @781574155,

As you quoted, if `broker.publisher` decorator is used, we publish whatever returned value including `None`. 

If we make an excuse and exclude `None` from publishing, then tomorrow someone will come and complain that he expects `None` to be published. Or someone else may come and say that we have to exclude emptry string `""` also. The exclusion list will keep on growing and FastStream will become extremely opinionated.

Also, whether to publish `None` or not is a business logic. This is not same for everyone. As mentioned in README, you need to take care of business logic yourself.

I am going to close this issue.

**Comment by Lancetnik** [comment]
> @Lancetnik I hope you agree with my replies here

Totally!

But, I faced with such request many times, so, I think, we should make a solution in a some way

Probably, smth like `OptionalResponse` should be fine

```python
@broker.subscriber(...)
@broker.publisher(...)
async def handler():
    body: Any | None = await do_optional_stuff()
    return OptionalResponse(body, suppress_publication=body is None)
```

Or smth like `EmptyReponse`

```python
@broker.subscriber(...)
@broker.publisher(...)
async def handler():
    body: Any | None = await do_optional_stuff()
    if body is None:
        return EmptyReponse()
    return body
```

I think, we should discuss possible options with community

**Comment by 781574155** [comment]
Essentially, @Lancetnik your suggestion has no difference to @kumaranvpl 's solution. Either way, business login has to include mq processing logic . A better solution should be add an bool swich param to @rabbit_router.publisher function ,which defaults  to send None message to mq.

**Comment by Lancetnik** [comment]
@781574155 indeed. Seems like we should do nothing. As @kumaranvpl said, optional publishing is your business logic and it can't be encapsulated in any flag in the framework code. Also, it is very opinionated: what's the difference between `None`, `""`, `[]` or `0`? All of them are correct body to publish, so why we should have a flag for specific value? There are too many flag already exists

So, if your business logic has an optional publishing, it is much clear (for all code readers) to implement it via direct publishing inside under `if` statement: https://faststream.airt.ai/latest/getting-started/publishing/direct/

**Comment by Lancetnik** [comment]
> Either way, business login has to include mq processing logic.

Sorry, but I can't agree. You have 2 ways here:

1) Publishing is a correct step of your business logic and you shouldn't be afraid to use it as an usecase of your interactor
2) Your business logic know nothing about MQ. All MQ interactions are encapsulated in Presentation layer (you handler code):

```python
@broker.subscriber(...)
async def handler(msg):
     response = await do_business_stuff(msg)
     if response:
          await publisher.publish(response, ....)
```
