### ISSUE TITLE
Bug: custom logger no longer working since 0.5.31 

### ISSUE THREAD

**Issue by yann-combarnous** [airtai/faststream#1959]
**Describe the bug**
Since 0.5.31, some FastStream logs are no longer using custom logger passed.

**How to reproduce**
Include source code:

```python
from faststream import FastStream
from faststream.confluent import KafkaBroker
from my_custom_logger import logger

broker = KafkaBroker(logger=logger)
app = FastStream(broker, logger=logger)
...
```

**Expected behavior**
- logs should be in JSON and using passed logger, see log format in 0.5.30
```
{"extra": {}, "level": "debug", "timestamp": "2024-12-03T10:30:07.245457Z", "message": "FETCH [faststream-0.5.30#consumer-6] [thrd:sasl_ssl://eventhub-namespace.servicebus.windows.net:9093/b]: sasl_ssl://eventhub-namespace.servicebus.windows.net:9093/0: Topic my_topic [0] MessageSet size 0, error \"Success\", MaxOffset 85, LSO 85, Ver 4/4"}
```

**Observed behavior**
- logs are string formatted in 0.5.31:

```
%7|1733219914.207|FETCH|faststream-0.5.31#consumer-10| [thrd:sasl_ssl://eventhub-namespace.servicebus.windows.net:9093/b]: sasl_ssl://eventhub-namespace.servicebus.windows.net:9093/0: Topic mytopic [0] MessageSet size 0, error "Success", MaxOffset 8272, LSO 8272, Ver 2/2
```

**Environment**
Running FastStream 0.5.31 with CPython 3.12.7 on Darwin

**Comment by Lancetnik** [comment]
@yann-combarnous seems like it is confuent debug messages. Do you really need them?

**Comment by yann-combarnous** [comment]
> @yann-combarnous seems like it is confuent debug messages. Do you really need them?

They are debug messages, which used to be honoring the DEBUG_LEVEL in 0.5.30 as well. So ideally, we would be able to choose as in 0.5.30, based on debug level.
