### ISSUE TITLE
Bug: ASGI Support don't worked on Windows

### ISSUE THREAD

**Issue by fennr** [airtai/faststream#1962]
**Describe the bug**
На версии 0.5.31 asgi требует наличия gunicorn. Это не позволяет использовать библиотеку под windows. Зависимость кажется избыточной и breaking changes плохо ложится на изменения патча.
На 0.5.30 все работает корректно.

**How to reproduce**

```python
from faststream.nats import NatsBroker
from faststream.asgi import AsgiFastStream, make_ping_asgi

broker = NatsBroker()

app = AsgiFastStream(
    broker,
    asgi_routes=[
        ("/health", make_ping_asgi(broker, timeout=5.0)),
    ]
)
...
```

**Additional context**
![изображение](https://github.com/user-attachments/assets/31b48312-36a8-472f-bb94-d8f07b4dbd02)

**Comment by Lancetnik** [comment]
promores
