### ISSUE TITLE
Bug: Dynamic subscriptions parsing incompatible with faststream.nats.fastapi.NatsRouter

### ISSUE THREAD

**Issue by saschnet** [airtai/faststream#1970]
Version 0.5 introduces dynamic subscription, currently only documented in https://github.com/airtai/faststream/releases/tag/0.5.0

The example fails when using the broker from faststream.nats.fastapi.NatsRouter. In this case, the message is not parsed in the handling function.

**How to reproduce**
```python
import asyncio

from faststream.nats import TestNatsBroker
from faststream.nats.fastapi import NatsRouter
from pydantic import BaseModel

router = NatsRouter()


class TestModel(BaseModel):
    val: bool


test_model = TestModel(val=True)


async def handler_method(m: TestModel) -> TestModel:
    assert isinstance(m, TestModel)
    return m


async def start() -> None:
    async with TestNatsBroker(router.broker) as br:
        subscriber = router.broker.subscriber("dynamic")
        subscriber(handler_method)
        router.broker.setup_subscriber(subscriber)
        await subscriber.start()

        await br.request(subject="dynamic", message=test_model)

        await subscriber.close()


asyncio.run(start())
```
**Expected behavior**
The above code should not fail.

**Observed behavior**
The code fails at `assert isinstance(m, TestModel)` as m is an instance of the raw NatsMessage.
Using the regular NatsBroker instead of the fastapi extension, the above code succeeds.

**Comment by Lancetnik** [comment]
@saschnet try to register subscriber via stream router instead of underlying broker `subscriber = router.subscriber("dynamic")  # instead of router.broker.subscriber(...)` - it should works fine

**Comment by saschnet** [comment]
Thanks a lot. It solves the issue.

For the records: With a router dynamic subscriptions work as follows:
```python
subscriber = router.subscriber("dynamic")
subscriber(handler_method)
router.broker.setup_subscriber(subscriber)
await subscriber.start()
await br.request(subject="dynamic", message=test_model)
await subscriber.close()
```

Might be worth mentioning, when this feature is added to the documentation.
