### ISSUE TITLE
Feature: Add option to override "instrumenting_module_name" in Opentelemetry 

### ISSUE THREAD

**Issue by rishabhc32** [airtai/faststream#1993]
**Is your feature request related to a problem? Please describe.**
Currently the `faststream.opentelemetry.middleware._get_tracer` hardcodes the `instrumenting_module_name` to `__name__`. Adding an option to override the `instrumenting_module_name` will be beneficial.

https://github.com/airtai/faststream/blob/684ef1aef9e0ebcf7c4a053525bdbbe6ca2a7c6e/faststream/opentelemetry/middleware.py#L331-L336

**Describe the solution you'd like**
Add a config option to override the opentelemetry `instrumenting_module_name`.

**Describe alternatives you've considered**
Currently I am overriding it by doing the following:
```python
@dataclass
class _FaststreamTraceProvider(TracerProvider):
    trace_provider: TracerProvider
    instrumenting_module_name: str = "opentelemetry.instrumentation.faststream"

    def get_tracer(self, instrumenting_module_name: str, *args, **kwargs) -> Tracer:
        return self.trace_provider.get_tracer(self.instrumenting_module_name, *args, **kwargs)

broker.add_middleware(
    RabbitTelemetryMiddleware(
        tracer_provider=_FaststreamTraceProvider(
            logfire_instance.config.get_tracer_provider()
        )
    )
)
```

This feels more like a hack rather than a proper solution.

**Comment by Lancetnik** [comment]
@draincoder can you please take a look here?

**Comment by draincoder** [comment]
Hi! Please tell me why you needed to redefine `instrumenting_module_name`?

**Comment by rishabhc32** [comment]
@draincoder I am using https://logfire.pydantic.dev/ for Opentelemetry spans. There the otel scope name was visible as `middleware` as the current full scope name is `faststream.opentelemetry.middleware`, which is kind of ambiguous. So I changed it to `opentelemetry.instrumentation.faststream`.

**Comment by draincoder** [comment]
@rishabhc32 

In this case, it is more logical to simply replace `__name__` with `open telemetry.instrumentation.faststream` without the possibility of redefinition, since the name was initially not very well chosen. I think that in this case, no one will need to redefine `opentelemetry.instrumentation.faststream` anymore.

As for the **logfire**, are there any other problems with **OpenTelemetry** in **FastStream**? Is the context being propagated correctly? What dependencies are needed?

**Comment by rishabhc32** [comment]
> In this case, it is more logical to simply replace `__name__` with `opentelemetry.instrumentation.faststream` without the possibility of redefinition, since the name was initially not very well chosen. I think that in this case, no one will need to redefine `opentelemetry.instrumentation.faststream` anymore.

Yes that can be done. Opentelemetry also suggests using  a fixed string that can be imported where needed and used consistently as the name of the tracer.

Other than this minor inconvenience logfire with works fine Faststream.

**Comment by rishabhc32** [comment]
@draincoder Also I think we should set `instrumenting_library_version` to faststream's version.

**Comment by draincoder** [comment]
@rishabhc32 Thanks a lot for the comment, it will be corrected soon. I have already seen the **OpenTelemetry** recommendations and I completely agree.

It turns out that **logfire** even has an example of integration with **FastStream** https://logfire.pydantic.dev/docs/integrations/faststream/

**Comment by rishabhc32** [comment]
> It turns out that **logfire** even has an example of integration with **FastStream** https://logfire.pydantic.dev/docs/integrations/faststream/

Yead it was added today only.
https://github.com/pydantic/logfire/issues/667#issuecomment-2545882312
