### ISSUE TITLE
Feature: Remove ambiguity from faststream logging docs

### ISSUE THREAD

**Issue by rishabhc32** [airtai/faststream#1994]
**Is your feature request related to a problem? Please describe.**
Currently in the Faststream logging docs it suggests that there are two loggers namely `faststream` and `faststream.access`.
But actually the logger is not `faststream.access` but `faststream.access.{broker}`. E.g. `faststream.access.rabbit`.

This should be added to the docs to remove ambiguity.

https://faststream.airt.ai/latest/getting-started/logging/#application-and-access-logging

**Describe the solution you'd like**
Add to docs that the default broker logger have a format of `faststream.logger.{broker}`.

**Comment by Lancetnik** [comment]
It is not correct to be honest. I am still thinking, how we should name loggers for each broker in mutliple broker case:

```python
FastStream(RabbitBroker(), RabbitBroker())
```

So, I didn't edit documentation due it is not the final view. Probably, we should just remove broker name mention at all?

Brokers' logger guarantee delivery by Context

```python
async def handler(logger: Logger): ...
```

But not access by name

**Comment by rishabhc32** [comment]
> Probably, we should just remove broker name mention at all?

Yeah that would be better.

**Comment by Lancetnik** [comment]
@rishabhc32 could you please make a such PR? I am out of home for a few days and it's not comfortable to edit smth by phone 😄

**Comment by rishabhc32** [comment]
Add @Lancetnik Please check https://github.com/airtai/faststream/pull/1995.
