### ISSUE TITLE
Use `Depends` from FastAPI in `@broker.subscribe`

### ISSUE THREAD

**Issue by AlexPetul** [airtai/faststream#2008]
Hi there, i have a question regarding using di. Right now i have a few services in FastAPI and in all the dependencies i use FastAPI's function `Depends`. For example:

```python
from fastapi import Depends

async def get_user(
    user_id: Annotated[
        str,
        Header(
            alias="X-User-ID",
            description=(
                """
                User ID that performs the request.
                By default the value is set by an API Gateway.
                """
            )
        )
    ],
    storage: Annotated[redis.Redis, Depends(get_storage)]
) -> User:
    ....
```

As far as i understood, if i want to use di in my consumer, i should use `Depends` from faststream (or fast_depends). Here i have a confusion, because on the one hand i don't want to rewrite all of my dependencies with fast_depends, and on the other hand i cannot use existing dependencies in my listener. What is the best solution for this case?

**Comment by Lancetnik** [comment]
FastStream compatible with **FastAPI** depends if you are using FastAPI integration - https://faststream.airt.ai/latest/getting-started/integrations/fastapi/#handling-messages
