### ISSUE TITLE
Provide the option to disable data validation

### ISSUE THREAD

**Issue by danielgafni** [airtai/faststream#444]
Data validation is sometimes not desirable due to negative performance impact

It would be useful if `fastkafka` provided a way to disable it using using [model_construct](https://docs.pydantic.dev/latest/usage/models/#creating-models-without-validation).

**Comment by Sternakt** [comment]
This could be solved by writing a custom encoder/decoder that uses model_construct, please checkout [Creating a custom encoder/decoder guide](https://fastkafka.airt.ai/docs/0.7.0/guides/Guide_07_Encoding_and_Decoding_Messages_with_FastKafka/#3-custom-encoder-and-decoder) and see if this will fit your use-case
