### ISSUE TITLE
how to define the different structure of the messages when consume one topoc?

### ISSUE THREAD

**Issue by sevenpy** [airtai/faststream#460]
I have another product client, and it will product different structure messages.
So, how do I define the structure? Or not use pydantic, Just use json to load messages?
Thanks!

**Comment by Sternakt** [comment]
Hi!

Please take a look at [this guide on encoding/decoding messages](https://fastkafka.airt.ai/docs/guides/Guide_07_Encoding_and_Decoding_Messages_with_FastKafka/)
My guess is that you probably want to implement a custom decoder for your consumer function which differentiates between two message types.
