### ISSUE TITLE
Write FastStream application and test examples for guides

### ISSUE THREAD

**Issue by rjambrecic** [airtai/faststream#491]

**Comment by Lancetnik** [comment]
Please, import your tests in the `tests/faststream_gen_examples` directory
For now, only `tests/` directory tests runs

**Comment by Lancetnik** [comment]
Also, probably should we create a separated repo for this reason when the package will be published?

**Comment by davorrunje** [comment]
There is a separate repo for code generation, but we'll have examples in this repo because the code generation must work with all versions. Each version of the lib will have its own examples because API might change.
