### ISSUE TITLE
Add lifespan context manager like FastAPI

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#531]

**Comment by Lancetnik** [comment]
Why we should add it?
And which lifecycle points it should be triggered (before/after broker start, before/after broker close)?

**Comment by Lancetnik** [comment]
Also, is it the same with #521?

**Comment by davorrunje** [comment]
> Also, is it the same with #521?

yes, it is the duplicate

**Comment by davorrunje** [comment]
> Why we should add it? And which lifecycle points it should be triggered (before/after broker start, before/after broker close)?

Lifespan context manager is more convenient when you have to do some cleanup on broker close. That was changed about a year ago in FastAPI and it makes sense to me. See:

https://fastapi.tiangolo.com/advanced/events/

**Comment by Lancetnik** [comment]
We have more places to user would like to interact, so in which one lifespan should start and end?
Before broker connection up and after broker connection down, I suppose?

**Comment by davorrunje** [comment]
> We have more places to user would like to interact, so in which one lifespan should start and end? Before broker connection up and after broker connection down, I suppose?

yes

**Comment by Lancetnik** [comment]
Little note: we should pass extra CLI options to the lifespan too (like in the `on_startup` hook`

**Comment by davorrunje** [comment]
Just released: https://github.com/airtai/faststream/releases/tag/0.3.0rc0
