### ISSUE TITLE
Fix reentrancy problems with testing

### ISSUE THREAD

**Issue by sternakt** [airtai/faststream#556]
Skipped tests for reentrancy are at `tests/brokers/kafka/test_test_reentrancy.py`
Should be enabled and passing when reentrancy problems are resolved

**Comment by Lancetnik** [comment]
We need to correct behavior attempt subscriber case: subscribers, created inside test function are not removing from global broker object and failure other tests

**Comment by Lancetnik** [comment]
We still have a tests failing this case: https://github.com/airtai/faststream/blob/main/tests/brokers/kafka/test_test_reentrancy.py#L61 and 
https://github.com/airtai/faststream/blob/main/tests/brokers/rabbit/test_test_reentrancy.py#L62
So, we need to remove or support them

**Comment by Lancetnik** [comment]
Copy of #1036
