### ISSUE TITLE
Cover `docs/docs_src/` scripts by tests

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#570]

**Comment by Lancetnik** [comment]
There are a lot of tests to write

**Comment by davorrunje** [comment]
@Lancetnik did you fix this last week?

**Comment by Lancetnik** [comment]
There are a little bit more

**Comment by Lancetnik** [comment]
You can watch by current coverage with coverage budge link: https://smokeshow.helpmanual.io/321e0k6u5d3d5n6e3g50/
