### ISSUE TITLE
Fix faststream docs gen producing wrong asyncapi

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#638]
Publishers and subscribers in the doc should be named after the topics they are connected to, and that is not the case in the generated docs
The topic name is described in the "channel specific info"

Schema is generated in https://github.com/airtai/faststream/blob/main/faststream/kafka/asyncapi.py#L31

**Comment by Lancetnik** [comment]
@Sternakt here is a my naming rules suggestion

```python
from faststream.kafka import KafkaBroker

broker = KafkaBroker()


@broker.subscriber("test-topic")
async def simple_handler():
    """
    test-topic/SimpleHandler
    test-topic/SimpleHandler/Message
    SimpleHandler/Message/Payload
    """


@broker.subscriber("test")
async def test_handler():
    """
    test/Handler
    test/Handler/Message
    Handler/Message/Payload
    """


@broker.subscriber("test")
async def handle_test():
    """
    test/Handle
    test/Handle/Message
    Handle/Message/Payload
    """


@broker.subscriber("test")
@broker.subscriber("test2")
async def handle_multi():
    """
    test/HandleMulti
    test/HandleMulti/Message

    test2/HandleMulti
    test2/HandleMulti/Message

    HandleMulti/Message/Payload
    """


@broker.subscriber("test", title="custom_name")
async def handle_manual():
    """
    custom_name
    custom_name/Message
    custom_name/Message/Payload
    """


def filter_naming():
    @broker.subscriber("test", filter=lambda m: m.content_type == "application/json")
    async def handle_json():
        """
        test/Handle
        test/Handle/Message  (payload oneOf)
        """

    @broker.subscriber("test")
    async def handle_default():
        """
        test/Handle
        test/Handle/Message  (payload oneOf)
        """

    """
    HandleJson/Message/Payload
    HandleDefault/Message/Payload
    """


from pydantic import BaseModel


class PydanticPayload(BaseModel):
    ...

@broker.subscriber("test")
async def handle_pydantic(msg: PydanticPayload):
    """
    test/HandlePydantic
    test/HandlePydantic/Message
    PydanticPayload
    """


# Publisher

@broker.publisher("test")
async def handler():
    """
    test/Publisher
    test/Publisher/Message
    test/Publisher/Message/Payload
    """


@broker.publisher("test", title="custom_publisher")
async def handler():
    """
    custom_publisher
    custom_publisher/Message
    custom_publisher/Message/Payload
    """

@broker.subscriber("test")
async def handler() -> PydanticPayload:
    """
    test/Publisher
    test/Publisher/Message
    PydanticPayload
    """


# RMQ Case

from faststream.rabbit import RabbitBroker

broker = RabbitBroker()

@broker.subscriber("test")
async def handler():
    """
    test/_/Handler
    test/_/Handler/Message
    test/_/Handler/Message/Payload
    """



@broker.subscriber("test", "topic")
async def handler():
    """
    test/topic/Handler
    test/topic/Handler/Message
    test/topic/Handler/Message/Payload
    """

...
```

**Comment by Lancetnik** [comment]
1) subject name
2) message name
3) payload name

**Comment by Sternakt** [comment]
Looks fine, I have two objections:

1. In these cases:
```
@broker.subscriber("test")
async def test_handler():
    """
    test/Handler
    test/Handler/Message
    Handler/Message/Payload
    """


@broker.subscriber("test")
async def handle_test():
    """
    test/Handle
    test/Handle/Message
    Handle/Message/Payload
    """
```

I would still keep the whole function name, not remove topic from it, seems that we are adding non necessary complexity into the parsing and naming otherwise

2. In the filter case, how do we decide the function name that will be used in the documentation, lets say they are named something more complex:

```
def filter_naming():
    @broker.subscriber("test", filter=lambda m: m.content_type == "application/json")
    async def parse_json_msgs():
        """
        test/Handle
        test/Handle/Message  (payload oneOf)
        """

    @broker.subscriber("test")
    async def default_handler():
        """
        test/Handle
        test/Handle/Message  (payload oneOf)
        """

    """
    HandleJson/Message/Payload
    HandleDefault/Message/Payload
    """
```
Should there still be a `test/Handle` or something else in the docs?

**Comment by Lancetnik** [comment]
1) I suggest to remove topic name from the function name
2) I thought about looking for same prefix for functions with filters, but, probably, we can use the first occured name

**Comment by Sternakt** [comment]
I may be nitpicking, but what about something like this, do we: remove all occurrences in string, only remove when suffix/prefix, remove when it's a standalone verb

```@broker.subscriber("data")`
async def save_data_to_database():
    """
    test/SaveToDatabase or SaveDataToDatabase or SaveToBase
    test/Handler/Message
    Handler/Message/Payload
    """
```
Obviously all occurrences is a bit naive, but just to show that this unecessarily complicates the logic, I would rather keep the whole function name

2. I agree, although, we could use a format like this:
topic:HandleFunc1/HandleFuncN...
And in rabbit case:
queue/exchange:HandleFunc1/HandleFunc2

**Comment by Lancetnik** [comment]
1) well, probably, we can leave the function name originally and do nothing with it. Looks like a best solution, especially, cuz user can manually change name directly, it just a default logic
2) I still think that the prefix logic is a better decision, but we should document this behavior

**Comment by Sternakt** [comment]
So, here is the compiled proposition for naming based on the discussion:

# Async Endpoint Naming Rules

Endpoints should follow the &lt;topic&gt;/&lt;handler&gt; naming expression. The topic name will remain as it was defined, and the handler name will be defined in a camel case convention.

## Basic Example

The most basic endpoint example would be this:

```python
@broker.subscriber("test-topic")
async def simple_handler():
    pass
```

The naming for this case will be:

- **Endpoint name:**
  - test-topic/SimpleHandler
- **Message name:**
  - test-topic/SimpleHandler/Message
- **Payload name:**
  - SimpleHandler/Message/Payload

## Handling Multiple Topics

In the case of handling multiple topics, the handler name will stay the same, but the topic prefix will change accordingly:

```python
@broker.subscriber("test")
@broker.subscriber("test2")
async def handle_multi():
    pass
```

First endpoint naming will be:

- **Endpoint name:**
  - test/HandleMulti
- **Message name:**
  - test/HandleMulti/Message
- **Payload name:**
  - HandleMulti/Message/Payload

Second endpoint naming will be:

- **Endpoint name:**
  - test2/HandleMulti
- **Message name:**
  - test2/HandleMulti/Message
- **Payload name:**
  - HandleMulti/Message/Payload

## Custom Names

Custom names can be used to override the default naming convention:

```python
@broker.subscriber("test", title="custom_name")
async def handle_manual():
    pass
```

- **Endpoint name:**
  - custom_name
- **Message name:**
  - custom_name/Message
- **Payload name:**
  - custom_name/Message/Payload

## Filter Naming

Naming the filters will be done as naming separate topics, so the endpoints will be all documented in the AsyncAPI specification:

```python
@broker.subscriber("test", filter=lambda m: m.content_type == "application/json")
async def handle_json():
    pass

@broker.subscriber("test")
async def handle_default():
    pass
```

First endpoint naming will be:

- **Endpoint name:**
  - test/HandleJson
- **Message name:**
  - test/HandleJson/Message
- **Payload name:**
  - HandleJson/Message/Payload

Second endpoint naming will be:

- **Endpoint name:**
  - test/HandleDefault
- **Message name:**
  - test/HandleDefault/Message
- **Payload name:**
  - HandleDefault/Message/Payload

## Pydantic Payload Description

When we define the structure of the payload using pydantic, the name of the payload will reflect the name of the pydantic class that defines the payload structure:

```python
from pydantic import BaseModel

class PydanticPayload(BaseModel):
    ...

@broker.subscriber("test")
async def handle_pydantic(msg: PydanticPayload):
    pass
```

- **Endpoint name:**
  - test/HandlePydantic
- **Message name:**
  - test/HandlePydantic/Message
- **Payload name:**
  - PydanticPayload

## RMQ Case

In the RabbitMQ case, we don't have topics but queues and exchanges, so the naming must include both. The <topic> now becomes <queue>/<exchange>. If the exchange is not defined, it will default to "_":

```python
@broker.subscriber("test")
async def handler():
    pass
```

- **Endpoint name**:
  - test/_/Handler
- **Message name:**
  - test/_/Handler/Message
- **Payload name:**
  - test/_/Handler/Message/Payload

```python
@broker.subscriber("test", "topic")
async def handler():
    pass
```

- **Endpoint name:**
  - test/topic/Handler
- **Message name:**
  - test/topic/Handler/Message
- **Payload name:**
  - test/topic/Handler/Message/Payload

**Comment by Lancetnik** [comment]
I am still not sure about filtering case. Looks like oneOf payload type is the best solution, but I can't image channel naming rule in this case

**Comment by Lancetnik** [comment]
@Sternakt can we use the first function handler name in the `filtering` case for now? I am still adhere to one subscriber for filters, but with the `oneOf` payload, but I am really confused about naming in this case.. Probably, using the first occured is OK

**Comment by Sternakt** [comment]
> @Sternakt can we use the first function handler name in the `filtering` case for now? I am still adhere to one subscriber for filters, but with the `oneOf` payload, but I am really confused about naming in this case.. Probably, using the first occured is OK

Yes, I am implementing it like that right now
I am having some issues with the parsing of payloads, but I should resolve it in the morning

Also, including the exchange in the rabbit naming case requires some rework on the tests but it should be ready for merge soon

**Comment by Lancetnik** [comment]
dirty-equals allows you to use regex as a string template, so we can use it in naming tests to support variations
Also, don't forget to check FastAPI integration case naming too
