### ISSUE TITLE
Control concurrency per-subscriber

### ISSUE THREAD

**Issue by chrisgoddard** [airtai/faststream#693]
I understand that I can run the app with a number of workers - but what if there is a particular subscriber function that I only want running one at a time? For instance, if it's communicating with a downstream service that's single threaded. Is it possible to still have multiple workers for the whole application while limiting a specific subscriber so that it won't be invoked multiple times concurrently?

**Comment by davorrunje** [comment]
From discord:

Lancetnik:
If you running your application as a single process you should use asyncio.Lock for this reason.
If you running multiple workers you should take a look at disturbed lock algorithms (like RedLock on top of Redis).

Davor Runje:
@Good Kiwi if using Kafka, you can set a fixed key on all produced messages and they will always be consumed by the same subscriber. It is a bit specific to Kafka and you must have control over producing, but I hope it helps.
