### ISSUE TITLE
CSS fixes to make API(@broker.subscriber) look better?

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#726]

**Comment by Lancetnik** [comment]
What does it mean?) Is it you want to fix?

![Image](https://github.com/airtai/faststream/assets/44573917/8f60369a-e4bc-4b14-81fe-fe068d5489ec)

**Comment by kumaranvpl** [comment]
Yup, exactly. APIs text looks off in docs and doesn't pops up when compared
to surrounding text.

**Comment by Lancetnik** [comment]
We can just remove #!python prefix
Without it it'll be looks like `@broker.subscriber`

**Comment by Lancetnik** [comment]
But syntax highlighted text looks better for me 😃

**Comment by Lancetnik** [comment]
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme

**Comment by kumaranvpl** [comment]
@Lancetnik Sure. This is lowest in priority. We can close it now.
