### ISSUE TITLE
Bug: When using your own broker connection parameters, the connection is not taken into account.

### ISSUE THREAD

**Issue by Jaroslav2001** [airtai/faststream#737]
## When using your own broker connection parameters, the connection is not taken into account.

Due to the multiple inheritance problem
This problem applies to all brokers.

This error occurs due to using the parent class RabbitLoggingMixin rather than BrokerAsyncUsecase

`RabbitBroker.mro()`
```
<class 'faststream.rabbit.broker.RabbitBroker'>
<class 'faststream.rabbit.shared.logging.RabbitLoggingMixin'>
<class 'faststream.broker.core.asyncronous.BrokerAsyncUsecase'>
<class 'faststream.broker.core.abc.BrokerUsecase'>
<class 'abc.ABC'>
<class 'typing.Generic'>
<class 'faststream.broker.core.mixins.LoggingMixin'>
<class 'object'>
```

**Comment by Lancetnik** [comment]
@Jaroslav2001 thx for the Issue! It is not inheritance problem, but you are right: it's a real misconduct
