### ISSUE TITLE
Bug: FastAPI KafkaRouter broken `batch` consuming

### ISSUE THREAD

**Issue by jamshi-dev** [airtai/faststream#745]
**Describe the bug**
With fast api serialization I am having issue with batch consuming. The error shows
```
fastapi.exceptions.RequestValidationError: [{'type': 'list_type', 'loc': ('body',), 'msg': 'Input should be a valid list', 'input': {'msg': [{'id': 85}]}, 'url': 'https://errors.pydantic.dev/2.4/v/list_type'}]
```

**How to reproduce**
Include source code:

```python
from faststream.kafka.fastapi import KafkaRouter
from pydantic import BaseModel, Field

event_router = KafkaRouter("localhost:9092", setup_state=False)

class ItemUpdateEvent(BaseModel):
    id: int = Field(
        frozen=True,
        description="Id of the updated item in table.",
    )

@event_router.subscriber("elastic-sink", group_id="elastic-sync", batch=True)
async def on_elastic_sink(msgs: List[ItemUpdateEvent]):
    logging.info(f"Got msg batch: {msgs}")
    bulk_data = []
    for msg in msgs:
    ....
```

**Expected behavior**
The input expected before calling  field validate should be `'input':  [{'id': 85}]`.  Instead request body passed in is `{'msg': {'msg': [{'id': 85}]}}`  which transforms to ` {'msg': [{'id': 85}]}` before calling field validate and results in the validation error.

**Observed behavior**
[{'type': 'list_type', 'loc': ('body',), 'msg': 'Input should be a valid list', 'input': {'msg': [{'id': 85}]}, 'url': 'https://errors.pydantic.dev/2.4/v/list_type'}]

**Comment by Lancetnik** [comment]
As I can see, you are trying serialize dict structure as a list. '{ "msg": [...] }' is not a valid list, so I suppose, serialization behavior is correct

**Comment by Lancetnik** [comment]
Can you show me the way, how you publish message?

**Comment by jamshi** [comment]
event_router.broker.publish(ItemUpdateEvent(id=1), 'elastic-sink')

**Comment by Lancetnik** [comment]
Thanks, I'll see how fix it

**Comment by jamshi** [comment]
Thanks for the support
