### ISSUE TITLE
Bug: cannot create more than one function that subscribes to the same topic when using subscriber decorator

### ISSUE THREAD

**Issue by marknutter** [airtai/faststream#757]
**Describe the bug**
Creating two different functions that subscribe via the subscribe decorator and subscribe to the same topic result in one subscriber overwriting the other, making it impossible to have allow two different functions to subscribe to the same topic.

**How to reproduce**
Include source code:

```python
from faststream import FastStream
from faststream.kafka import KafkaBroker

broker = KafkaBroker("localhost:9092")

app = FastStream(broker)

@broker.subscriber("test")
async def first_test_subscriber(body):
    print(body)

@broker.subscriber("test")
async def second_test_subscriber(body):
    print(body)
```

And/Or steps to reproduce the behavior:

1. Run the code above using FastStream's cli
2. Take note of the number of "waiting for messages" logs being output (should be 1 instead of two):
```
$ poetry run faststream run faststream:app --reload --log-level debug
2023-09-26 09:58:56,468 INFO     - Started reloader process [59246] using WatchFiles
2023-09-26 09:58:56,808 INFO     - FastStream app starting...
2023-09-26 09:58:57,888 INFO     - test |            - `FirstTestSubscriber` waiting for messages
2023-09-26 09:58:59,648 INFO     - FastStream app started successfully! To exit, press CTRL+C
2023-09-26 09:59:56,933 INFO     - FastStream app shutting down...
```

**Expected behavior**
Both subscribers should be initiated when running the FastStream app

**Observed behavior**
Only one subscriber is initiated when running the FastStream app

**Environment**
Running FastStream 0.1.1 with CPython 3.9.12 on Darwin

**Comment by Lancetnik** [comment]
You can't create copy of your subscriber. Subscriber overloading exists only for the [filtering](https://faststream.airt.ai/latest/getting-started/subscription/filtering/) feature reason.
But, in Kafka case, you can specify different `group_id` for this subscribers - and it will register them separately

**Comment by marknutter** [comment]
As of the latest version, adding a group_id parameter to the subscriber decorator ensures that two different functions can be subscribed to the same topic. Closing this issue.
