### ISSUE TITLE
Feature: support path-based arguments

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#764]
Some brokers (**RMQ**, **NATS**, **Redis**, etc) allows you to consume messages by *pattern*
So, we can support path-based arguments in this case

```python
from faststream import FastStream, Path
from faststream.nats import NatsBroker

broker = NatsBroker()
app = FastStream(broker)

@broker.subscriber("subject.{user_id}")
async def handler(msg, user_id: str = Path()):
    ...
```

**Comment by snorfalorpagus** [comment]
I can see this being a useful feature.

How would the different pattern matching syntaxes for RMQ/NATS/Redis/etc be handled? For example, [RMQ](https://www.rabbitmq.com/tutorials/tutorial-five-python.html) supports either `*` (one word) or `#` (none or more words) as wildcards, while [Redis uses glob-style patterns](https://redis.io/commands/psubscribe/) like `*` (none or more characters) and `h[ae]llo`. Would this just have to make an assumption (e.g. `subject.{user_id}` translates to `subject.*` in RMQ and `subject.*` in Redis)?

**Comment by Lancetnik** [comment]
It was just a little thought to add in backlog, without any details.
Sure, you are right {user_id} just a pattern for '.*' RMQ and '\.\w' Redis case
There are no any problem to support different syntax for different brokers via ABCParser inheritors, so I have a plan to create unified syntax, but not all of its' features will be supported at all brokers cases
