### ISSUE TITLE
Bug: multiple subscriptions are not properly documented

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#765]
**Describe the bug**

But according to the documentation [1] and examples [2] multiple subscription decorators should be supported.
[1] https://faststream.airt.ai/0.1.5/getting-started/subscription/#multiple-subscriptions
[2] https://github.com/airtai/faststream/blob/main/examples/e03_miltiple_pubsub.py#L9

**How to reproduce**
Include source code:

```python
from faststream import FastStream
from faststream.annotations import Logger
from faststream.rabbit import RabbitBroker

broker = RabbitBroker("amqp://guest:guest@localhost:5672/")
app = FastStream(broker)


@broker.subscriber("test-queue")
@broker.subscriber("another-queue")
async def handle(msg, logger: Logger):
    logger.info(msg)
    return "Response"


@app.after_startup
async def test():
    await broker.publish("Hello!", "test-queue")
```

**Expected behavior**

The output log:

```
2023-09-26 13:25:12,909 ←[32mINFO    ←[0m - FastStream app starting...
2023-09-26 13:25:13,005 ←[32mINFO    ←[0m - default | test-queue    |            - `HandleTest-Queue` waiting for messages
2023-09-26 13:25:13,014 ←[32mINFO    ←[0m - default | another-queue |            - `HandleAnother-Queue` waiting for messages
2023-09-26 13:25:13,029 ←[32mINFO    ←[0m - FastStream app started successfully! To exit, press CTRL+C
2023-09-26 13:25:13,031 ←[32mINFO    ←[0m - default | another-queue | 77c11a9be7 - Received
2023-09-26 13:25:13,033 ←[32mINFO    ←[0m - default | another-queue | 77c11a9be7 - Hello!
2023-09-26 13:25:13,034 ←[32mINFO    ←[0m - default | another-queue | 77c11a9be7 - Processed
```

**Observed behavior**

In the log, you can see the "another-queue" queue, even though "test-queue" is actually used. I see "test-queue" correctly used in RabbitMQ management, so this is probably due to the order of the decorators. Or did I get it wrong?

**Additional context**

https://www.reddit.com/r/Python/comments/16pc38l/comment/k29fbj5/?utm_source=share&utm_medium=web2x&context=3

**Comment by Lancetnik** [comment]
What's the problem? This way you creates 2 consumer by one function. You can publish a message to one queue or another and trigger the correct consumer

```python
from faststream import FastStream
from faststream.annotations import Logger
from faststream.rabbit import RabbitBroker

broker = RabbitBroker("amqp://guest:guest@localhost:5672/")
app = FastStream(broker)

@broker.subscriber("test-queue")
@broker.subscriber("another-queue")
async def handle(msg, logger: Logger):
    logger.info(msg)
    return "Response"

@app.after_startup
async def test():
    await broker.publish("Hello!", "test-queue")
    await broker.publish("Hello!", "another-queue")
```

```console
INFO     - default | test-queue    | 85e5f34f5a - Received
INFO     - default | test-queue    | 85e5f34f5a - Processed
INFO     - default | another-queue | ac700f3fcd - Received
INFO     - default | another-queue | ac700f3fcd - Processed
```

I can't undestand the behavior you expect

**Comment by Lancetnik** [comment]
Probably, you are testing not with the latest version. I checked it just now and all log messages are displaying correctly.

**Comment by Lancetnik** [comment]
It wasn't a documentation bug, it just a logging bug, don't confuse people. And it is already fixed.
Btw, all things described in the docs are supported and tested

**Comment by Lancetnik** [comment]
Also, #757 Issue has nothing to do with the current problem
It was about different functions subscription copy, not about multiple decorators

**Comment by davorrunje** [comment]
Sorry, my mistake. The bug report came from Reddit, I just copied it here last night without checking it first.
