### ISSUE TITLE
Feature: NATS watch by KV and Object storage via decorator

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#782]

**Comment by theobouwman** [comment]
So is this feature merged or still open?
We would like to watch on a key, not clear if that is possible now...

**Comment by Lancetnik** [comment]
Originally, we were planning to implement this feature in the PR, but didn't do it. This feature is in backlog for now.

**Comment by pySilver** [comment]
@Lancetnik do you have any directions on how-to implement it even in most naive way?

**Comment by Lancetnik** [comment]
It's not a big deal, we just need to create an extra [NATS handler class](https://github.com/airtai/faststream/blob/big-refactor/faststream/nats/handler.py), but it requires to release 0.5.0 at first (it can takes a couple off weeks 😢)
