### ISSUE TITLE
Fix google analytics issue because of mike redirection

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#815]

**Comment by Lancetnik** [comment]
We can remove redirects at all using mike copy strategy
This way I creates a full-copy version of the latest one, so we'll have 3 versions (latest, 0.2.0, 0.1.0), but without any redirects

**Comment by davorrunje** [comment]
The problem is that people land most often on /, and there it has to redirect to latest or 0.x. In any case, the medium/source gets lost and we have all direct traffic in GA right now.

**Comment by kumaranvpl** [comment]
Use meta tags redirection instead of js redirection

**Comment by davorrunje** [comment]
some 30% is not set, that's fine
