### ISSUE TITLE
Bug: cannot import name 'raise_fastapi_validation_error'

### ISSUE THREAD

**Issue by kreneskyp** [airtai/faststream#858]
**Describe the bug**
Error running faststream CLI.  Error raised on all commands

**How to reproduce**
Include source code:

```
faststream --version
```

And/Or steps to reproduce the behavior:

1. run any faststream cli command

**Expected behavior**
Should report faststream version

**Observed behavior**
Exception raised 

**Screenshots**
```
root@8761fe349f39:/var/app# faststream --version
Traceback (most recent call last):
  File "/usr/local/bin/faststream", line 5, in <module>
    from faststream.__main__ import cli
  File "/usr/local/lib/python3.11/site-packages/faststream/__main__.py", line 1, in <module>
    from faststream.cli.main import cli
  File "/usr/local/lib/python3.11/site-packages/faststream/cli/main.py", line 10, in <module>
    from faststream.cli.docs.app import docs_app
  File "/usr/local/lib/python3.11/site-packages/faststream/cli/docs/app.py", line 10, in <module>
    from faststream.asyncapi.generate import get_app_schema
  File "/usr/local/lib/python3.11/site-packages/faststream/asyncapi/generate.py", line 17, in <module>
    from faststream.broker.fastapi.router import StreamRouter
  File "/usr/local/lib/python3.11/site-packages/faststream/broker/fastapi/__init__.py", line 1, in <module>
    from faststream.broker.fastapi.route import StreamMessage, StreamRoute
  File "/usr/local/lib/python3.11/site-packages/faststream/broker/fastapi/route.py", line 29, in <module>
    from faststream._compat import raise_fastapi_validation_error
ImportError: cannot import name 'raise_fastapi_validation_error' from 'faststream._compat' (/usr/local/lib/python3.11/site-packages/faststream/_compat.py)
```

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.

faststream 0.2.5

Same error in both python 3.11 docker container and in WSL with python 3.11.5

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by Lancetnik** [comment]
@kreneskyp can you please add reprodusable dockerfile?

**Comment by davorrunje** [comment]
@kreneskyp I just tried the same in the fresh virtual environment and here is my output:

```
$ faststream --version
Running FastStream 0.2.5 with CPython 3.11.5 on Linux
$ python --version
Python 3.11.5
$ pip list
Package           Version
----------------- -------
annotated-types   0.6.0
anyio             4.0.0
click             8.1.7
fast-depends      2.2.1
faststream        0.2.5
idna              3.4
pip               23.2.1
pydantic          2.4.2
pydantic_core     2.10.1
setuptools        65.5.0
sniffio           1.3.0
typer             0.9.0
typing_extensions 4.8.0
uvloop            0.18.0
watchfiles        0.21.0

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: pip install --upgrade pip
(.env-3.11) davor@tr3970x-1:/work/davor/projects/airt/faststream$ 
```

Can you please share the result of `pip list`?

**Comment by kreneskyp** [comment]
Tracked it down to an incompatibility with pydantic 1.10.  I need finish updating to v2 on my end.

**Comment by Lancetnik** [comment]
@kreneskyp unfortynatelly, this is not PydanticV1 compatibility bug. Sometimes [this function](https://github.com/airtai/faststream/blob/main/faststream/_compat.py#L50C1-L50C1) returns `True` even if library is not installed and this occured in your case. But I can't reproduce this behavior regularly and have no idea why python lie to me...

**Comment by kreneskyp** [comment]
Hmm. In any case I worked through my remaining Pydantic v2 issues and was able to successfully run faststream.  Possibly related to another lib that needed an update?

```
root@1f1e0a5187a3:/var/app# faststream --version
Running FastStream 0.2.5 with CPython 3.11.6 on Linux
```

**Comment by kreneskyp** [comment]
I also updated FastAPI with Pydantic 2.x.  It's working now so no need to investigate further.  Thanks!
