### ISSUE TITLE
Bug: unable to register multiple publishers with just exchange and routing key

### ISSUE THREAD

**Issue by reritom** [airtai/faststream#875]
**Describe the bug**
In my context, the publishing service only cares about the exchange and the routing key. The routing key doesn't necessarily match the queue name.

If I try to register two publishers with the same exchange and different routing keys, only one gets registered.

**How to reproduce**
```python
# main.py
from faststream import FastStream
from faststream.rabbit import RabbitBroker
from faststream.rabbit.shared.schemas import RabbitExchange

broker = RabbitBroker(
    url="testuser:testpassword@myhost:1234/myvhost",
    virtualhost="myvhost",
)
faststream_app = FastStream(title="My app", broker=broker)
exchange = RabbitExchange("my-exchange", durable=True)

pub_1 = broker.publisher(
    exchange=exchange,
    routing_key="rk-1",
    title="Message1",
)

pub_2 = broker.publisher(
    exchange=exchange,
    routing_key="rk-2",
    title="Message2",
)
```

And/Or steps to reproduce the behavior:

1. Copy code into main.py
2. Install `faststream[rabbit,docs]==0.2.6
3. run `faststream docs gen main:faststream_app`

**Expected behavior**
That both publishers should be registered, and that they are visible in the docs (and usable in general).

**Observed behavior**
The generated documentation shows only the first publisher registered, and both publishers publish using the same routing key as the first registered publisher

```json
{
  "asyncapi": "2.6.0",
  "defaultContentType": "application/json",
  "info": {
    "title": "My app",
    "version": "0.1.0",
    "description": ""
  },
  "servers": {
    "development": {
      "url": "testuser:testpassword@myhost:1234/myvhost",
      "protocol": "amqp",
      "protocolVersion": "0.9.1"
    }
  },
  "channels": {
    "Message1": {
      "servers": [
        "development"
      ],
      "bindings": {
        "amqp": {
          "is": "routingKey",
          "bindingVersion": "0.2.0",
          "queue": {
            "name": "",
            "durable": false,
            "exclusive": false,
            "autoDelete": false,
            "vhost": "/"
          },
          "exchange": {
            "name": "my-exchange",
            "type": "direct",
            "durable": true,
            "autoDelete": false,
            "vhost": "/"
          }
        }
      },
      "publish": {
        "bindings": {
          "amqp": {
            "cc": "",
            "ack": true,
            "bindingVersion": "0.2.0"
          }
        },
        "message": {
          "$ref": "#/components/messages/Message1:Message"
        }
      }
    }
  },
  "components": {
    "messages": {
      "Message1:Message": {
        "title": "Message1:Message",
        "correlationId": {
          "location": "$message.header#/correlation_id"
        },
        "payload": {
          "$ref": "#/components/schemas/Message1Payload"
        }
      }
    },
    "schemas": {
      "Message1Payload": {}
    }
  }
}
```

(Side note: I would expect the virtualhost defined if the broker to be defined on the exchange, or at least some way to specify it, but couldnt find a way)

**Environment**
Running FastStream 0.2.6 with CPython 3.9.12 on Darwin

**Comment by Lancetnik** [comment]
Publishers were designed to forbid create multiple publishers to one target. To setup various `routing_key` with the one publisher, please use it directly by `publusher.publish(msg, routing_key="...")`

Btw, virtualhost is not defined automatically indeed, I'll fix it soon

**Comment by reritom** [comment]
If I understand correctly then I won't be able to generate asyncapi documentation about any of the specifics of routing keys or payloads. In my case most flows have ingress exchanges that accept various routing_key+payload_schema combinations, so the single "schema" attribute on the publisher can't support all of the different payload types, same for the routing key.

Is there any plan to support this sort of usecase?

**Comment by Lancetnik** [comment]
Sounds reasonable, I'll take a look that I can do with it
