### ISSUE TITLE
Feature: schema generate enable connection arguments rather than connection string url

### ISSUE THREAD

**Issue by ptrba** [airtai/faststream#895]
# Current behaviour

At the time of writing (faststream==0.2.8) the RabbitBroker constructor signature reads:

```python
 def __init__(
        self,
        url: Union[str, URL, None] = "amqp://guest:guest@localhost:5672/",
        *,
        virtualhost: str = "/",
        max_consumers: Optional[int] = None,
        protocol: str = "amqp",
        protocol_version: Optional[str] = "0.9.1",
        security: Optional[BaseSecurity] = None,
        **kwargs: Any,
    )
```

which implies that an empty url is allowed. `**kwargs` arguments are correctly passed down to `connect_robust`:

```python
async def connect_robust(
    url: Union[str, URL, None] = None,
    *,
    host: str = "localhost",
    port: int = 5672,
    login: str = "guest",
    password: str = "guest",
    virtualhost: str = "/",
    ssl: bool = False,
    loop: Optional[asyncio.AbstractEventLoop] = None,
    ssl_options: Optional[SSLOptions] = None,
    ssl_context: Optional[SSLContext] = None,
    timeout: TimeoutType = None,
    client_properties: Optional[FieldTable] = None,
    connection_class: Type[AbstractRobustConnection] = RobustConnection,
    **kwargs: Any,
)
```
Thus we can use ``**kwargs``rather than the url to provide connection parameters. This works all fine. However, `faststream/asyncapi/generate.py:get_app_broker_server` will fail at line 140:

```python
elif len(broker.url) == 1:
```
because broker.url is `None`. 

# Desired behaviour

It is understood that every underlying broker technology uses different **kwargs, to build their internal actual connection string. The issue here is, that the url used for the schema generation is not exactly the same thing as the connection string. I actually ran into this issue because I did not want to display the connection string password in the asyncapi schema and decided to use **kwargs for providing the connection parameters. It is definitely not desired to display the full connection string in the api documentation.

One way to get around this issue is the introduce a new argument to the Broker constructor:
```python
server_url: list[str]|str|None 
```
used in in `get_app_broker_server` in case no url is specified.

Another way is to simply not display any server in the schema if url is None.

Yet another idea is to render the connection without username:password and parameters.

A combination of these approaches would also be feasible an fit all needs of customizability.

# Current workaround

Here is a monkey patch resolving the issue for RabbitBroker:

```python
def get_app_broker_server(*argv, **kwargs):
    url = make_url(
        login="****",
        password="****",
        host=args["host"],
        port=args["port"],
        virtualhost=args["virtualhost"],
        ssl=args["ssl"],
    )
    return {
        "development": faststream.asyncapi.generate.Server(
            url=str(url),
            protocol=url.scheme,
            protocolVersion=args["protocol_version"],
        )
    }

setattr(
    faststream.asyncapi.generate, "get_app_broker_server", get_app_broker_server
)
broker = faststream.rabbit.fastapi.RabbitBroker(**args)

```

**Comment by Lancetnik** [comment]
@ptrba thank you for the Issue! Indeed, I just missed this RMQ usecase. Also, your notice gave me an idea: what do you think about special AsyncAPI broker argument like `asyncapi_url` (or smth like that) just to replace the real connection url in a schema explicitly?

**Comment by Lancetnik** [comment]
Btw, construct RMQ url from arguments directly should be implemented as well
