### ISSUE TITLE
Feature: schedule/cron/periodic for spawn processes and ignite machinery

### ISSUE THREAD

**Issue by yokotoka** [airtai/faststream#913]
What if use something like that on input instead of subscribe?
https://schedule.readthedocs.io/en/stable/

Often we need a start point like periodic task triggers, not only user interactions

**Comment by Lancetnik** [comment]
Hi, @yokotoka! Unfortunatelly, we have no plans to implement tasks scheduling right in the **FastStream** core, but **taskiq** integration via **FastStream** plugin is on process. For now, you can integrate your application with smth like **rocketry** to use tasks scheduling: https://github.com/Lancetnik/Propan/blob/main/examples/scheduling/rocketry.py

**Comment by Lancetnik** [comment]
@yokotoka the job is done! Now you can use native taskiq integration to schedule your tasks:
https://github.com/taskiq-python/taskiq-faststream/tree/master
