### ISSUE TITLE
Feature: Observability 

### ISSUE THREAD

**Issue by grski** [airtai/faststream#916]
We'd love to use faststream as part of our application however one thing that popped out for consideration is observability.

We currently live in the opentelemetry world and honeycomb, with some sentry on top of that. Sentry could be integrated through their basic sdk I think, however it'd be nice to have opentelemetry support of some sorts OOB. 

Given it's industry standard it should be helpful to a lot of people making observability way easier.

We also thought about getting some kind of kind of a heartbeat from the workers? We'd like to know eg. if it died and wondering if it should be handled eg. a level higher on container level or sth or is it already avaialble? 

Awesome work so far.

**Comment by davorrunje** [comment]
Thanx for the suggestion, we'll start working on it very soon.

**Comment by dearkafka** [comment]
voting for this feature

**Comment by davorrunje** [comment]
We are looking into it right now.

**Comment by Kludex** [comment]
> We are looking into it right now.

Did you find something there? 👀

**Comment by Lancetnik** [comment]
I found a project trying to implement this feature: https://github.com/ashambalev/opentelemetry-instrumentation-faststream

But, after `0.5.0` release, I hope, we can implement it as a broker middleware and distribute as optional dependency.

**Comment by Lancetnik** [comment]
Assigned to @draincoder
