### ISSUE TITLE
Bug: Auto offset commit for kafka not working.

### ISSUE THREAD

**Issue by haripriyarhp** [airtai/faststream#923]
**Describe the bug**
Auto offset commit does not seem to work for Kafka. 
I have set the below properties for the @broker.subscriber
 auto_commit = True
 auto_commit_interval_ms = 1000

**Expected behavior**
 When I shut down the faststream app using CTRL+C for graceful shutdown, the offset for the subscriber needs to be committed when shutting down. It does not happen and always get the below message. 

**Observed behavior**
From logs
```
Heartbeat failed: local member_id was not recognized; resetting and re-joining group
Heartbeat session expired - marking coordinator dead
Marking the coordinator dead (node 0)for group vectron-topic-multiplexer.
OffsetCommit failed for group group_name due to group error ([Error 25] UnknownMemberIdError: group_name), will rejoin
OffsetCommit failed for group group_name due to group error ([Error 25] UnknownMemberIdError: group_name), will rejoin
Failed to commit on finallization: CommitFailedError: ('Commit cannot be completed since the group has already\n            rebalanced and assigned the partitions to another member.\n            This means that the time between subsequent calls to poll()\n            was longer than the configured max_poll_interval_ms, which\n            typically implies that the poll loop is spending too much\n            time message processing. You can address this either by\n            increasing the rebalance timeout with max_poll_interval_ms,\n            or by reducing the maximum size of batches returned in poll()\n            with max_poll_records.\n            ', 'Commit cannot be completed since the group has already rebalanced and may have assigned the partitions to another member')
```

**Comment by sternakt** [comment]
Hi haripriyarhp,

Thanks for reporting the issue. I'll investigate the auto offset commit problem in the faststream app on Monday. The default behavior should include automatic offset commits, and we haven't faced similar issues before. I appreciate your patience, and I'll get back to you with a solution or further details soon.

Just to clarify:

1. The logs you are seeing are shown on app shutdown or when starting up a new instance of the app?
2. Have you tried increasing `max_poll_interval_ms`? It sounds like it may be set too low.

**Comment by haripriyarhp** [comment]
Hi @sternakt, Thanks for the reply. 
1. The logs are seen when I shutdown the app with CTRL+C.
This is the list of parameters I have set
auto_commit = True,
auto_commit_interval_ms = 1000,
heartbeat_interval_ms = 10000,
session_timeout_ms = 30000,
max_poll_interval_ms = 300000,
max_poll_records = 1

**Comment by sternakt** [comment]
Hi @haripriyarhp,

Unfortunately I am having a hard time reproducing this issue.

I have tried with a simple consumer setup with the addition of mentioned parameters, like so:
```python
import asyncio
import random

from faststream import FastStream, Logger
from faststream.kafka import KafkaBroker
from pydantic import BaseModel, Field

version = "0.1.0"
title = "My FastStream service"
description = "Description of my FastStream service"


class Name(BaseModel):
    name: str = Field(..., description="Name of the person")


broker = KafkaBroker(
    "localhost:9092",
)

app = FastStream(broker, title=title, version=version, description=description)


@broker.subscriber(
    "names",
    description="Consumes messages from names topic and produces messages to greetings topic",
    auto_commit=True,
    auto_commit_interval_ms=1000,
    heartbeat_interval_ms=10000,
    session_timeout_ms=30000,
    max_poll_interval_ms=300000,
    max_poll_records=1,
)  # type: ignore
async def on_names(msg: Name, logger: Logger) -> None:
    result = f"hello {msg.name}"
    logger.info(f"Processing {msg.name} (sleep for 10s)...")
    greeting = Greeting(greeting=result)
    await asyncio.sleep(10)
    logger.info(f"Done processing {msg.name}")
```
And graceful shutdown (CTRL+C) never results in the mentioned exception.

Is it possible for you to share your application implementation details and kafka broker settings?

**Comment by haripriyarhp** [comment]
@sternakt : To add some information, I use the consumer from faststream but use produce method from confluent_kafka. This is because the publish from faststream is not fast enough for our usecase. So I consume an event from kafka which points to the location of a json file. This json file contains around 50K records. Using publish from faststream takes more than 1.5 minutes to publish these 50k records, hence I use confluent_kafka.produce to send records.

**Comment by sternakt** [comment]
Okay, are you using `producer.flush()` when shutting down the application?
This is the recommended procedure when shutting down confluent producers, documented [here](https://docs.confluent.io/kafka-clients/python/current/overview.html#synchronous-writes)

I recommend adding `@app.after_shutdown` hook that does just that to the FastStream application, you can find the documentation for lifespan hooks [here](https://faststream.airt.ai/0.2/getting-started/lifespan/hooks/?h=hook)

**Comment by haripriyarhp** [comment]
I tried setting as suggested. But still get the same error
```
@app.on_shutdown
async def trigger_flush_producer():
    producer.flush()

```
2023-11-13 14:36:25,039 INFO     - FastStream app shutting down...
2023-11-13 14:36:25,094 Heartbeat failed: local member_id was not recognized; resetting and re-joining group
2023-11-13 14:36:25,094 Heartbeat session expired - marking coordinator dead
2023-11-13 14:36:25,094 Marking the coordinator dead (node 0)for group _group_name_.
2023-11-13 14:36:25,173 OffsetCommit failed for group _group_name_ due to group error ([Error 25] UnknownMemberIdError: _group_name_), will rejoin
2023-11-13 14:36:25,173 OffsetCommit failed for group _group_name_ due to group error ([Error 25] UnknownMemberIdError: group_name), will rejoin
2023-11-13 14:36:25,173 Failed to commit on finallization: CommitFailedError: ('Commit cannot be completed since the group has already\n            rebalanced and assigned the partitions to another member.\n            This means that the time 
between subsequent calls to poll()\n            was longer than the configured max_poll_interval_ms, which\n            typically implies that the poll loop is spending too much\n            time message processing. You can address this either 
by\n            increasing the rebalance timeout with max_poll_interval_ms,\n            or by reducing the maximum size of batches returned in poll()\n            with max_poll_records.\n            ', 'Commit cannot be completed since the gro
up has already rebalanced and may have assigned the partitions to another member')
2023-11-13 14:36:25,203 INFO     - FastStream app shut down gracefully.
```

```

**Comment by sternakt** [comment]
Hi @haripriyarhp ,
I am still having difficulty reproducing the error.

It would be really helpful if you could share a reproducible code that exhibits the mentioned behaviour, otherwise I'm afraid I cannot proceed because without it it's just guesswork from my side.

Thanks a bunch! Let me know if you have any questions.

**Comment by spataphore1337** [comment]
We faced a similar problem and experimentally came to the following conclusions:

When you are running CPU-bound tasks, you have a blocked event loop and healthchecks cannot be sent. So when you finish processing a function, healtcheckds drop and you lose the connection. There are exactly two ways to deal with this:

1) specify in the subscriber parameters the session_timeout_ms argument for how long your task will be processed directly. For example, if you set time.sleep(N) in the handler, you should specify session_timeout_ms > N in the subscriber arguments, and then the processing will be successful. Important: this is the solution when using an **asynchronous handler**;
2) if you have a synchronous CPU-bound task and you don't need to use anything asynchronous inside the handler, then you can **use a synchronous handler** without specifying a parameter in the subscriber. That is, we literally remove the word async from the function and get the desired result.
