### ISSUE TITLE
Usage: Pass app's module rather than file path.

### ISSUE THREAD

**Issue by Jufik** [airtai/faststream#929]
**Is your feature request related to a problem? Please describe.**

Not a "real" problem, just smth that feels incredibly odd and unpythonic:

`fastream run src/path/to/python/module/__init__:variable_name` (without the `.py` extension)
(either using `/` or `.`)

Having to put the `src` or the `__init__` feels just wrong.... 
Your app can end up in `.venv/lib/[.......]` or any other place, the CLI should just leverage python's module resolution to get this done.

**Describe the solution you'd like**

Should be able to start the app with
`fastream run module.import.string:my_variable`

**Feature code example**

In the CLI, rather than the "get_app_path", "try_import_app", smth like:

```python
import importlib
from faststream import FastStream
from faststream.exceptions import FastStreamException  # TODO

module_path, application_name = app.split(":")

# Raises a ModuleNotFoundError if not found
module = importlib.import_module(module_path)

# Raises an AttributeError if not found
app = getattr(module, application_name)

# Extra: checkout the app type
if not isinstance(app, FastStream):
    raise FastStreamException(
        f"{application_name} in {module_path} is not a FastStream application (found: {type(app)})"
    )
```

**Comment by Lancetnik** [comment]
I can't undestand the real problem
**FastStream** supports the following syntax
```shell
fastream run module.import.string:app_object
```
The same with uvocorn/gunicorn/etc way

**Comment by Lancetnik** [comment]
Well, I got it, thank you for the Issue!
I, think, we can just copy and reuse the original [uvicorn importer](https://github.com/encode/uvicorn/blob/master/uvicorn/importer.py)
Added it to backlog

**Comment by davorrunje** [comment]
The new release fixes this:

https://github.com/airtai/faststream/releases/tag/0.2.14
