### ISSUE TITLE
Feature: Schema Registry support

### ISSUE THREAD

**Issue by harochau-gamemod** [airtai/faststream#964]
Some Kafka libraries like [**confluent-kafka-python**](https://github.com/confluentinc/confluent-kafka-python),  https://github.com/marcosschroh/python-schema-registry-client and https://github.com/lsst-sqre/kafkit provide various schema registry integration capabilities (HTTP client for schema registry, caching schema registry requests, serialization/deserialization, Avro, Protobuf, JSON-schema support)

It would be nice to have such capabilities built-in with declarative style API.
Further more, I suggest providing both schema-first (use model.avro files) and code-first implementations (generate and register avro schema from Pydantic models or Dataclasses using https://github.com/marcosschroh/dataclasses-avroschema) of schema registry integration.

Using default code example, I envision the following usage pattern.

```python
from fastapi import FastAPI
from dataclasses_avroschema.avrodantic import AvroBaseModel

from faststream.kafka.fastapi import KafkaRouter
from faststream.kafka.schema_registry import SchemaRegistryConfig

router = KafkaRouter(
"localhost:9092",
schema_registry_config=SchemaRegistryConfig(
    format="avro",
    subject_naming_strategy="topic-key-value",
    schema_storage_strategy="from-pydantic-model",
    url="localhost:8081"
))

class Incoming(AvroBaseModel):
    m: dict

@router.subscriber("test")
@router.publisher("response")
async def hello(m: Incoming):
    return {"response": "Hello, world!"}

app = FastAPI(lifespan=router.lifespan_context)
app.include_router(router)
```

**Describe alternatives you've considered**
Each application may try to implement it's own integration with schema registry

**Comment by Lancetnik** [comment]
I am not a big Kafka specialist, but your code example with `SchemaRegistryConfig` looks great. @sternakt what do you think about this feature?

**Comment by davorrunje** [comment]
We are currently creating a new Kafka broker based on the Confluent library. We'll look into this as soon as the new broker support is finished.

**Comment by davorrunje** [comment]
@devova can we close this issue? Is it working for you?

**Comment by davorrunje** [comment]
Opening a new issue https://github.com/airtai/faststream/issues/1297 and closing this one.
