### ISSUE TITLE
Feat: make Context FastAPI-compatible

### ISSUE THREAD

**Issue by davorrunje** [airtai/faststream#974]
**Describe the bug**
Provide a clear and concise description of the bug.

fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that typing.Annotated[logging.Logger, <faststream.utils.context.types.Context object at 0x14b66d180>] is a valid Pydantic field type. If you are using a return type annotation that is not a valid Pydantic field (e.g. Union[Response, dict, None]) you can disable generating the response model from the type annotation with the path operation decorator parameter response_model=None

https://github.com/airtai/faststream/pull/641#issuecomment-1819610180

**How to reproduce**
Include source code:

```python
from faststream import FastStream
...
```

And/Or steps to reproduce the behavior:

1. ...

**Expected behavior**
Explain what you expected to happen clearly and concisely.

**Observed behavior**
Describe what is actually happening clearly and concisely.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by Lancetnik** [comment]
Btw, make `Context` FastAPI - compatible option is a great idea
