### ISSUE TITLE
Docs: Fix broken ordered list

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#997]
https://faststream.airt.ai/latest/kafka/Publisher/

**Comment by Lancetnik** [comment]
@kumaranvpl is it closed by https://github.com/airtai/faststream/pull/1003/commits/49997459e127379072a2985061a866cd81a0ebbe?

**Comment by kumaranvpl** [comment]
> @kumaranvpl is it closed by [4999745](https://github.com/airtai/faststream/commit/49997459e127379072a2985061a866cd81a0ebbe)?

Yes @Lancetnik. I will close the issue now.
